### ISSUE TITLE
filter() happening after limit()?

### ISSUE THREAD

**Issue by gb-lin** [ExpressionEngine/ExpressionEngine#1059]
Say you have 10 Members in your system. Member 1, 2, 3, are Super Admins(role id 1) and Member 4 is Editor(role id 6) and rest of them are Member(role id 5).

If you run the following code you will get a count of 4 results but not 5 as I'd expect to get. Noticed this in EE5 when I keep getting 770 on a 5,000+ users system when trying to get the 1000 members through the filters.
```
<?php
	$count = ee('Model')->get('Member')->with('Roles')->filter('Roles.role_id', 'IN', [1, 5,])->limit(5)->all()->count();

	echo '<pre>';
	print_r($count);
	echo '</pre>';
?>
```

**Comment by intoeetive** [comment]
When you eager load models, internally SQL `JOIN` is performed so `limit()` function is being translated into SQL `LIMIT`

Which in case of one-to-many relationships can cause behavior that might look unexpected from user point of view, but technically is correct.

In the given example, if one of users has 2 roles assigned, fetching all 10 members internally would return 11 rows from SQL query. Setting limit to 5 sets this limit on query, returning 5 rows - but since one of members actually is represented by 2 rows, those 5 rows are actually representing 4 members

**Comment by gb-lin** [comment]
@intoeetive Got it. Thanks for the explanation. Can you think of any possible ways to make it so that we're not selecting 1 member multiple times because they have different roles?

**Comment by intoeetive** [comment]
There is `getAllMembers()` function on `Role` model, but since you need 2 roles, it is probably of little help here.

I'd thing your only way around would be to fetch all members, and `filter()` on the collection received. Not the most performant way, but can't think of anything good ATM.
