### ISSUE TITLE
Using 'Preview'causes signout when saved

### ISSUE THREAD

**Issue by dblvzn** [ExpressionEngine/ExpressionEngine#1060]
When editing an entry, if I use the '**Preview**' button, then close the **Preview** _and_ **Save** the entry, one of two things occur... either I get _signed out_ and returned to the login page, _or_ I get this message - "ERROR: This form has expired. Please refresh and try again."

ExpressionEngine CMS 6.0.3

Locally I am using **MAMP Pro 6.3** on a Mac which consists of **Apache 2.4.46**, **MySQL 5.7.32**, and **PHP 7.4.12**.

On production my host is utilizing **Apache 2.4.46**, **MariaDB 10.3.24**, and **PHP 5.6.40** (which I am surprised I have not changed to 7).

This is faithfully recreated on both environments. The url is **xxx/cp/publish/edit/entry/245**

**Comment by intoeetive** [comment]
This is most likely caused by you accessing the site via 'http:' and site URL set to 'https:' in system preferences (or the other way round). Or using completely different URL other than specified in system preferences.

That being said, we will be pushing out some updates to LivePreview as part of 6.1.0 that would change how things work

**Comment by intoeetive** [comment]
The updates mentioned have been released and the issue should be no longer relevant
