### ISSUE TITLE
Ability to Search Entries by url_title and entry_id 

### ISSUE THREAD

**Issue by nervecreative** [ExpressionEngine/ExpressionEngine#1071]
In some cases - the URL Title could be different than the Title of the entry, even though EE will auto create the url_title from the Entry's title. It would be a productivity enhancement if you url_title and entry_id could be used to search for entires.

**Comment by swierczek** [comment]
+1 to searching by entry ID

**Comment by dunnmj42** [comment]
+1 to searching by entry ID

**Comment by micnow** [comment]
+1 to searching by entry ID

**Comment by litzinger** [comment]
We actually trained our content editors to provide the entry_id when making bug reports because in several cases we have entries from more than 1 channel that have similar or identical titles, so referencing the ID is often faster. Being able to enter the ID into the Entry Manager search field would be a huge productivity boost.

**Comment by erinathop** [comment]
+1 to searching by entry ID
