### ISSUE TITLE
🚀 Gathering Feedback - File Manager

### ISSUE THREAD

**Issue by ops-andy** [ExpressionEngine/ExpressionEngine#1120]
Trying to organize community feedback regarding the File Manager. Please feel free to comment, link ideas, give suggestions, etc.
What are some things you'd like to see in the File Manager that currently don't exist?    
What things in the File Manager just need to be improved?    
Do we need to remove things from the File Manager?   
.... what else?

Related Issues:
* https://github.com/ExpressionEngine/ExpressionEngine/issues/301
* https://github.com/ExpressionEngine/ExpressionEngine/issues/259
* https://github.com/ExpressionEngine/ExpressionEngine/issues/65

**Comment by pyrobob83** [comment]
The biggest issue IMO (which several on Slack agree with) is there's no way to update a particular document without either having to _overwrite_ the existing file with an identical filename **or** go through the entire site and update the document in every place it's used or linked to.  If we could make it so references to files used the file_id rather than the filename and let the templating engine render out the actual HTML output, then we could theoretically offer the ability to replace a document with any other filename without having to update links across the site.

The simplest illustration I can think of is a restaurant with a menu PDF - no matter how many times you instruct editors to _overwrite_ the existing generically-named file (eg `menu.pdf`), they almost always just re-upload a new one in one place with a filename like `menu_june_2021.pdf` and then complain when they realize some other page is still linking to the old version.

Attached is the thread of a discussion we had a little while ago for more thoughts/input.

[file-manager-discussion-thread-may-21.txt](https://github.com/ExpressionEngine/ExpressionEngine/files/6592905/file-manager-discussion-thread-may-21.txt)

The commonly-suggested channel-entry method with relationships really isn't suitable because you can't do that from a WYSIWYG editor, nor can you upload a file directly in the editor - it's like a 3-step process so usability is massively impacted and you're limited to how you can link to files (ie, only via relationship).  Not to mention finding the exact file you're looking for via relationship is a nightmare if you have several named similar.

Referring to #301, I love the idea of subfolders BTW and a move to referencing files by file_id I'm guessing would help make that possible too

**Comment by blue-dreamer** [comment]
I have a few clients who regularly update an existing file or two with a newer version. Having a specific function to _replace_ an existing file would be less hassle and cognitive load than Upload > overwrite existing which can be confusing.

Not many of my clients add inline links to WYSIWYG fields (I tend to give them specific fields for entry file uploads) but I see the problem if the file name changes, changing file functions to use the ID would be better all round for most purposes.

If it went to using ID's the only issue I can see is when field data with embedded file links is imported into a fresh build, like when you migrate old site > new site. File ID's won't usually match here, perhaps there's a need for a mechanism that says if the ID and filename don't match then fall back to the file name for matching? Once a filename match has been found then reference it to the new ID.

**Comment by ic360-com** [comment]
Some useful additional options (not sure if they have been discussed / submitted anywhere already though):
 - "Show me where this file is linked from" (also use this in the Delete function, if it isn't already).
 - Thumbnail images for uploaded PDFs.
 - Delete files option in "View as Thumbnail" mode.

**Comment by liamcrean** [comment]
My one (often requested update) would be to removie the interstitial page (attached) from the upload process and assume that a user will want to upload mutiple files - at any time. Once uploaded perhaps it'd be a good time to then offer some kind of selection feature (one file field is limited, or multiple rows for grid / file grid for example). This function is not availale in the file manager either — it'd be a good start to allow it here first.

It's been a very strange UI feature of EE for over a decade. It serves very little function for something used so often - and is a real barrier to consice productive management of files, in particular management and upload of lots of images.

<img width="1499" alt="Screenshot 2021-10-11 at 12 37 18" src="https://user-images.githubusercontent.com/2526645/136822829-5d519b18-836e-4ef5-be3e-6cc389e844d9.png">

Thanks :)

**Comment by PaulBaileyAtChan** [comment]
- It's an obvious omission that when listing files in the FM, or searching, it doesn't show the upload directory a file is in. This has a lot of practical uses. This is covered in https://github.com/ExpressionEngine/ExpressionEngine/issues/98
- Also, I'd really like to see who uploaded a file. Again, this is an obvious omission. Also covered in https://github.com/ExpressionEngine/ExpressionEngine/issues/98
- The relationship between the upload directory and its ID should be obvious from the CP. Currently, I can see an inline file referred to as (for example) `{filedir_10}`, and there's no way to find out from within the CP which directory that is. A nice solution here would be to allow reference to an upload directory using a short name, rather than an automatically chosen ID, in the same way that channels are referred to using a short name (despite also having a unique ID). Having that semantic information in the code would help with clarity.
- Accept that it's more of an extension than an omission, but I'd _love_ to have support for sub-folders.
- The thumbnail view in EE6 is a nice idea, but the implementation is poor. The thumbnails themselves are tiny, and unhelpfully cropped. Also, the ordering of files in thumbnail view is unintuitive, and can't be modified.

**Comment by murtaugh** [comment]
[Image file fields: display thumbnails in their native aspect ratio](https://github.com/ExpressionEngine/ExpressionEngine/issues/867)

**Comment by robsonsobral** [comment]
[Ability to specify allowed File types on the File field](https://github.com/ExpressionEngine/ExpressionEngine/issues/485)

**Comment by robsonsobral** [comment]
[Allow cloning of manipulations between different file directories](https://github.com/ExpressionEngine/ExpressionEngine/issues/1247)

**Comment by blue-dreamer** [comment]
A couple from me:

File URL should be available in the File picker modal as well as File manager, that way an author would be able to open File browser, locate their file and copy the URL for pasting wherever.

Nice to have: ability to move files between upload  locations.

Nice to have: URL field for credit attribution, link is sometimes required by the image author.

**Comment by blue-dreamer** [comment]
Most of my own ideas have been echoed by everyone else :)

It would be good to look at having a file audit tool to help site admins weed out old and unused files, with options to delete. Older/larger sites do tend to hoard huge numbers of outdated files because nobody know which ones aren't used. There's also an eco angle saving energy as well :)

Possibly a contender as a Pro feature?

**Comment by PaulBaileyAtChan** [comment]
+1 for a file audit tool. It would be hugely useful as a first-cut. It wouldn't ever be a complete replacement for a human audit, but as a guide to where to look, a big time-saver.

**Comment by robsonsobral** [comment]
May I talk about boring stuff?

- append hashes to manipulated filenames, to avoid [caching issues](https://github.com/ExpressionEngine/ExpressionEngine/issues/1220);
- save hashes of uploaded files on database, so we can use the [`integrity` attribute](https://github.com/ExpressionEngine/ExpressionEngine/issues/1230);

**Comment by intoeetive** [comment]
Also: 
[Allow files to be moved to a new destination folder](https://github.com/ExpressionEngine/ExpressionEngine/issues/1657)
[New image manipulation option (crop_scale)](https://github.com/ExpressionEngine/ExpressionEngine/issues/79)

**Comment by murtaugh** [comment]
Just a bump on #301 — it would make migrating content into EE from WordPress easier.

**Comment by intoeetive** [comment]
[Allow admins to select a default behavior for automatically resolving image upload conflicts](https://github.com/ExpressionEngine/ExpressionEngine/issues/1839)

**Comment by intoeetive** [comment]
[Button to invoke upload dialog directly in modal when browsing the files in directory](https://github.com/ExpressionEngine/ExpressionEngine/issues/1679)

**Comment by PDXMan1** [comment]
When we switch to file_id could we have two "slugs" please when they show in a text-area:  {filedir_##}/{file_##}  That will give us max flexibility during the transition for older sites and long-time EE clients (we've had some of same our clients in EE for over 18 years).

Also, if there could be a "file-info" dot or icon that shows the actual URI/path of/to the file in EE fields (like a hover-state or tool-tip kind of thing) it would make life much easier for the client that is looking at:

<a href="{filedir_25}/{file_14895}">Monthly Statement</a>

.. and trying to figure out if the link is so this month's statement, or last month's. Or, if they need to share the direct link to the file with someone.

I would love to see the switch to file IDs vs titles in the publish/edit pages.

**Comment by intoeetive** [comment]
New File Manager has been released in ExpressionEngine 7.

Thank you everyone for the contributions. Without your participation and feedback, we would never be able to get where we are now.
