### ISSUE TITLE
“Invalid Selection” error on the multi select when choosing a selection with ’ character

### ISSUE THREAD

**Issue by t1mwillis** [ExpressionEngine/ExpressionEngine#113]
**Description of the problem**
When selecting an option in a multi select that has manually populated values, if one of those values includes a ’ like in Children’s Picture Book, that value will not be selectable and the entire field will throw an "Invalid Selection" error because the ’ is rendered differently in the database.

**How To Reproduce**
1. Create Grid field
2. Create Multi Select field with manually populated values and add that to Grid field.

3. Fill those values with the following:
Poetry
Traditional Verse
Fiction
Nonfiction
Prose
Literary Fiction
Genre Fiction
Creative Nonfiction
Young Adult Fiction
Children’s Picture Book

4. Add that field to a channel
5. Create new entry in that channel
6. Select "Children’s Picture Book" in that multi-select

**Error Messages**
When selecting the value in an entry you get an "Invalid Selection" error on the field and can't submit then entry.

When editing the field you get the below error:
<pre><code>
Notice
Undefined offset: 1
ee/legacy/fieldtypes/OptionFieldtype.php, line 113

Severity: E_NOTICE
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:119)
ee/legacy/core/Input.php, line 237

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:119)
ee/legacy/libraries/Functions.php, line 392

Severity: E_WARNING

</code></pre>

**Screenshot:**
![invalid](https://user-images.githubusercontent.com/33670137/51996184-3ed4e980-2482-11e9-8486-d524e0afdf18.png)

**Environment Details:**
 - Version: [e.g. 4.3.6]
 - PHP Version [e.g. 7.2.11]
 - MySQL Version [e.g. 5.6.34]
 - OS: [macOS]
 - Web Server: [Apache]

**Possible Solution**
Robin says: "And it’s a bug- though I thought this issue was dealt with years ago.  I suspect it came back."

**Comment by kevincupp** [comment]
Sorry for your trouble. I'm not sure your steps to reproduce are complete. For one, I can't reproduce with them, and it looks like this field is inside a Grid, not a standalone field in a channel as indicated in the instructions. The PHP errors you're seeing would also only happen if the field was inside a Grid. It sounds like there might be more going that contributed to this than what was outlined.

I'm also testing within the context of 5.1.3 because it's the latest, we recommend doing the same before reporting issues. The PHP errors you're seeing are likely already fixed: https://github.com/ExpressionEngine/ExpressionEngine/commit/9d3ed163f4ad70d4ee2844e898ddf03b66213be4

If you still see the errors after upgrading, could you provide complete steps to reproduce? The apostrophe might be a red herring, might have more to do with changing field settings/options over time.

**Comment by t1mwillis** [comment]
@kevincupp you are correct, this field was inside a grid per screenshot.

**Comment by t1mwillis** [comment]
@kevincupp I just tested this in 5.1.3 and it behaves as expected.
