### ISSUE TITLE
Site wide cache

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1185]
**Is your feature request related to a problem? Please describe.**

Do you remember Mark @croxton's [Stash](https://github.com/croxton/Stash)? Back in the day, it made a huge success due to the performance improvements it provided.

Among the several features of Stash, some of them are currently available on layout variables. However, there's one I miss a lot: [static site wide cache](https://github.com/croxton/Stash/wiki/Caching).

**Describe the solution you'd like**

Currently, both page and tag caches are limited to the URI, as we can see at `system\ee\legacy\libraries\Template.php`, line [1973](https://github.com/ExpressionEngine/ExpressionEngine/blob/d72309c3ebb05bc020abdda4f4f45453f1ab3394/system/ee/legacy/libraries/Template.php#L1968):

```
    /**
     * Cache items are prefixed with a hash of the URI or query string of
     * the current page so that tags can still be influenced by URI items
     * and still be cached
     *
     * @return	string	MD5 hash of current URL
     */
    protected function _get_cache_prefix()
    {
        $language = ee()->session->get_language();

        if (ee()->uri->uri_string != '') {
            return md5(ee()->functions->fetch_site_index() . $language . ee()->uri->uri_string);
        }

        return md5(ee()->config->item('site_url') . 'index' . $language . ee()->uri->query_string);
    }
```

It would be awesome to have a value as `site` to the [`cache` parameter](https://docs.expressionengine.com/latest/channels/entries.html#cache-refresh) to use in navigational elements, footers, sidebars and other reusable, globally visible page elements:

```
{exp:channel:entries limit="10" cache="site" refresh="60"}
```

It isn't the same as Stash, but bring us closer to it.

Mr. Croxton himself documented [common pitfalls, and how to avoid them](https://github.com/croxton/Stash/wiki/Caching#common-pitfalls-and-how-to-avoid-them), which could help to write the documentation.

**Describe alternatives you've considered**

There are some addons that can do this job, but...

**Teachability, Documentation, Adoption, Migration Strategy**

...to have a better caching strategy available out-of-the-box would be awesome! Together with #1145 (Memory Cache within DB Drivers), it would be great!

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by jcogs-design** [comment]
Could you explain a bit more about how you see this working?  
For example using your example... `{exp:channel:entries limit="10" cache="site" refresh="60"}` what is it you are hoping to cache
- the output of the tag itself?  If so - are you assuming `dynamic="no"`?  If not, do you cache based on what is in URI (i.e. EE's best attempt at guessing channel) and so actually have possibly multiple cached items (for each possible URL where this might be called) or simply what is output the first time you call this tag with these parameters?
- the parsed output of whatever is enclosed by opening / closing tags (this is perhaps closer to the stash original concept)?
- something else?

Presumably also there is a need to know if the cache is site-wide or MSM-wide?

Useful to know more about your thoughts on how this would be used in practice.

**Comment by robsonsobral** [comment]
Let's use 1, 2, 3.

1. this is already how `cache="yes"` works;
2. I don't think to get to close to stash, but to do baby steps.
3. keep everything the same as today, but give us the option to avoid repeating the processing of the same piece of code on every single URL;

`cache="msm"` could be an option, but not exactly on first release. Thinking on menus, headers, footers and sidebar, it's a huge improvement.

Trying to simplify my thoughts: when `cache="site"`, we ignore the URI on generating the hash of cache file name.

A little less complicated, @jcogs-design ?

**Comment by jcogs-design** [comment]
In your description for the `cache="site"` parameter you aim to disconnect the cache for a tag from its URI.  Such a disconnection would mean that the cache content for all uses would be set by the output generated by the first instance of the tag that EE encounters after whatever refresh period is specified for the tag has expired.  

We won't know which URI a user might be visiting when the `refresh=` time on that tag is reached; if the output of that tag is somehow based on the URI consequentially we will not know a-priori what data the cache will be holding, resulting in the other uses of that tag having quasi-random output.  I'm not sure how useful this would be.

If you somehow limit use of the setting of the cache value stored against the `cache="site"` parameter to only one tag in one template (for example by having an extra parameter such as `save_cache="yes"`) this would remove the ambiguity about what the cache contains, but I'm unclear how this would be enforced; if cannot enforce the limit and a site has more than one such tag defined then you are back to the 'random' content issue noted above.

In your original post you say:

> It would be awesome to have a value as site to the cache parameter to use in navigational elements, footers, sidebars and other reusable, globally visible page elements:

This suggests that rather you want to save these elements as temporary system wide constants - much as you would do if you put them into a `stash`.

You can do something like this using existing EE tools ... for example by putting the template output you want to cache either into a template variable, template partial or (if the code needs evaluation before saving) an embed that itself uses tag-caching of its content; then simply put suitable references into templates to the element used as required.

An alternative solution might be to provide for the definition of something similar to **layout variables** but defined at the site rather than template level, which perhaps then could be also cached.  Which sounds a bit like 'stash lite': I am not clear what the advantage of this approach would be over the template variable / partial / embed route - but if there is one then this might be useful as an EE built in solution / alternative.

**Comment by robsonsobral** [comment]
Here we go!

Being `$chunk` all outer content of the tag being cached.

```
$cfile = md5($this->remove_ee_comments($chunk))
```

The cache of tags is named using also its outer contents, which will be prefixed by the MD5 of URI and language. The same tag creates different cache files for different URIs. There's no way of doing what you suggested.

##  The proof

I created 2 templates for testing: `cache1.html` and `cache2.html`. Both have the same `{embed=test/menu}`:

```
<nav class="header-nav">
    {exp:channel:category_archive show_empty="no" disable="category_fields"
    style="nested" category_group="{global:cascade-menu-group}" class="header-nav__list" cache="yes" refresh="60"}
        {categories}
            {category_name}
        {/categories}

        {entry_titles}

<pre>
    channel_id: {channel_id}
    channel_name: {channel_name}
    channel_url: {channel_url}
</pre>


            <a href="{channel_url}/{url_title}">{title}</a><br />
        {/entry_titles}
    {/exp:channel:category_archive}
</nav>
```

After accessing `/test/cache1` twice, I got:

![image](https://user-images.githubusercontent.com/931642/127024677-9f6bbb44-45f6-42d7-82bc-48fe2ce290b3.png)

Then, `/test/cache2`:

![image](https://user-images.githubusercontent.com/931642/127024879-734ad823-ecef-4872-83b7-80ef8bb943c9.png)

On `cache3.html`, I called the same tag three times. The first 2, using the same arguments, but different indentation; and the first and the third using the same indentation but different arguments.

![image](https://user-images.githubusercontent.com/931642/127026409-3b29a9ce-03af-4504-8555-51960498d901.png)

After I enabled the page caching for `test/menu.html`, I tested again accessing `/test/cache1`, to trigger the cache creation, and the `/test/cache2`:

![image](https://user-images.githubusercontent.com/931642/127035084-d48fe17f-e869-4e7c-ac22-7159861f8b2d.png)

As you can see, the embed was completely parsed again.

## The epilogue

For a long time, I thought the cache on eecms considered the URI just when using `{segment_}` variables, but the truth is that it's far limited.

Better? Easier to understand? 🙂

**Comment by jcogs-design** [comment]
> There's no way of doing what you suggested.

Golly that is a lot of work to illustrate that using the embed suggestion won't work... but interesting to know all the same: I thought embeds had their own EE instance - doesn't make much sense for them to be cached against the URI of the calling template but I can see how / why that happens.  In the purist sense, that behaviour is verging on a bug I think...

Apart from demonstrating that the embed option cannot be used, I'm not sure it advances the case for the `cache="site"` parameter.  The issues raised about random content are not addressed by your observations: without getting that sorted I think we end up with a stronger case for defining a template definable **site variable** tag similar to **layout variable** but with cross-template persistance (and cacheability); such a thing is quite a long way from the proposed modification to caching though.

**Comment by robsonsobral** [comment]
I'm sorry, but I don't know how that would be different from your suggestion or your previous assumption about embed templates. In any case, private or wrong data can be cached. It's up to the developer to avoid doing that. Even today, [member variables can be cached](https://docs.expressionengine.com/latest/templates/engine.html#rendering-order) by mistake.

Or I'm missing your point?

**Comment by jcogs-design** [comment]
I think I understand what you are trying to achieve, and can see how it might be useful to be able to reuse stashed elements across multiple pages. My comments concern whether the right way to achieve the outcome you seek can be via modification to the cache function you describe. I think they are simply these points:

- If you disconnect the cache_key from a template (proxied in EE by the URI), then same cache key can be created by tags on different templates (indeed this seems to be what you intend by your proposed additional parameter).  However under these conditions there is no obvious way to control **which** of the multiple tags with the same cache_key create the content: by implication there is a need for the content of the tags to be parsed before saving (else you could just use template variables / partials to save the content), which implies that the tag to be cached in this way necessarily will generate different content on different templates.  Since you can't control which of the multiple eligible tags might generate the cache_key first after the previous cache'd content expires, you likewise will not be able to control what the content of the cache will be either from cache cycle to cache cycle.  This randomised behaviour is unlikely to be useful.
- If you park the randomised content issue and assume that some use case is established where the content of the cache is held consistent between different implementations of the tag, it not obvious what actual efficiency will come from eliminating  duplicated cache elements that would otherwise occur using the normal cache_key based on URIs model: sure there will be a small amount of cache storage saved due to the avoided duplication, but the time to retrieve cache will be same whether it is a 'site' cache or one tied to the URI, so unless cache storage itself is an operational issue for the site (?) the use of the central 'site' cache would not appear to offer any performance improvements over potentially redundant storage of multiple similar cache'd elements delivered by the current caching model.

Oddly your proposed outcome (that you can 'stash' the output of a tag parse activity and recall it multiple times across different templates pre-parse) makes more sense if you are **not** caching the template output - since for those instances use of the parsed tag output retrieved from the stash would most likely avoid some some SQL activity and so reduce server load somewhat - but this only happens if the template is being evaluated / parsed - if the output of the template is being read from a cache then these processing savings will not materialise.

So while I get the concept in the abstract, a practical use-case example where the tag cache change proposed delivers benefits that cannot be obtained in other ways remains mostly unclear, and for the edge case that I can imagine probably the solution is not a modification of the template caching system but the introduction of a new kind of persistent template variable.

**Comment by robsonsobral** [comment]
Apart from using a time variable as a parameter value or the database being updated between requests, how could the same tags with the same content to give different results?

Let's test it.

Given a template partial `test-menu`, where `{global:cascade-menu-group}` is an early parsed variable, let's call it on `test/cache4` and `test/cache5`.

```
<nav class="header-nav">
    {exp:channel:category_archive show_empty="no" disable="category_fields"
    style="nested" category_group="{global:cascade-menu-group}" class="header-nav__list" cache="yes" refresh="60"}
        {categories}
            {category_name}
        {/categories}

        {entry_titles}
            <a href="{channel_url}/{url_title}">{title}</a><br />
        {/entry_titles}
    {/exp:channel:category_archive}
</nav>
``` 

The IDs of the cache files are `md5(ee()->functions->fetch_site_index() . $language . ee()->uri->uri_string) . '+' . md5($this->remove_ee_comments($chunk))`, where `$chunk` is the matched data block, including opening/closing tags, spaces and line breaks.

On `test/cache4` and `test/cache5`, respectively:

- `fd477302802a4a73f0331e506bd3ce89+6a21d35002ae66a448a68f9f70eaf440`
- `1d8e40cc72077641da74e955adb4f189+6a21d35002ae66a448a68f9f70eaf440`

Same name, `6a21d35002ae66a448a68f9f70eaf440`; different suffixes.

Let's replace `{global:cascade-menu-group}` by `{segment_3}` and add `/5` to te URLs:

- `edbf22287bcf232e87fcfa7b8ac10a2b+6a21d35002ae66a448a68f9f70eaf440`
- `25d9980cb7bf1c534fc0b0c42bfaa6fe+6a21d35002ae66a448a68f9f70eaf440`

Same name as before, `6a21d35002ae66a448a68f9f70eaf440`; different suffixes.

Now, adding a single extra space between tag parameters. Changing from `exp:channel:category_archive show_empty="no"` to `exp:channel:category_archive  show_empty="no"`, we get:

- `edbf22287bcf232e87fcfa7b8ac10a2b+24a94b04683b7a7025ec6cd1b3d5fb4c`
- `25d9980cb7bf1c534fc0b0c42bfaa6fe+24a94b04683b7a7025ec6cd1b3d5fb4c`

Same **new** name, `24a94b04683b7a7025ec6cd1b3d5fb4c`; different suffixes.

(**github markdown parser doesn't show the extra space**)

So, we could change:

```php
$cfile = $this->_get_cache_prefix() . '+' . $cfile;
```

To something like:

```php
$cfile = $args['cache'] === 'site'
  ? md5(ee()->config->site_url() . $this->marker) . '+' . $cfile
  : $this->_get_cache_prefix() . '+' . $cfile;
```

Or `ee()->config->item('site_id')`... Whatever.

Your suggestion looks great for pure data, but, to me, it looks a total overkill for parsed markup. And I can't imagine a simpler way to save DB queries and processing for:

- a list of most seen entries on a sidebar;
- dynamic menus on header;
- a box of related content after old articles;
- list of new content on "read more";
- a box of the latest news...

If you can give an example of how this could be messed up, I'll appreciate!

**Comment by jcogs-design** [comment]
I am not proposing an implementation for the global variable: it is clear that the cache_key mechanism used by the current caching strategy would not be helpful, as was acknowledged a couple of posts ago - some other cache marking system would be required.  Concerns about how the cache_key might be generated is not something that has featured in this exchange so far; I'm not sure it is relevant (other than to agree it would need to be different to that used for tag cache).

As for an example, here is one:
```
<!-- navigator -->
<ul>
{exp:channel:entries channel="headliners" cache="site" refresh="60"}
    <li class="{if url_title == segment_1}active_menu_item{/if}"}>
        <a href="{url_title_path='sections'}">{title}</a>
    </li>
{/exp:channel:entries}
</ul>
````
The menu item assigned class `active_menu_item` will vary according to the URL active when the template fragment is evaluated.  Apriori the designer cannot know which url will be viewed first after the cache expires, and so the 'active' menu item will be set to a random value (which when retrieved by other visitors to the site may or may not reflect that user's location in site).

**Comment by robsonsobral** [comment]
I'm sorry if I put words in your mouth. It wasn't my intention.

I can't agree with this:

>  it is clear that the cache_key mechanism used by the current caching strategy would not be helpful, as was acknowledged a couple of posts ago - some other cache marking system would be required.

As I can't understand your example. Why would I cache for all the site something dependent of the url?!

I don't want to break or remove things which already work, but to add a new option for the cases the url doesn't matter.

**Comment by jcogs-design** [comment]
I'm not suggesting that **you** would do anything.  Simply that the `cache="site"` parameter you propose exposes a risk that in normal use you cannot be sure what result it will return since you can easily include within a cached item elements that are URL dependent, which means in turn when the cache is retrieved from a different URL the returned information may not be correct.  This seems to present an unnecessary complication that might cause problems for some users.  Further, as noted previously, since it is not obvious what performance benefit would come from the modified cache over what is already available the case for introducing such complications seems weak.

Not clear what about the example you don't understand: it generates a navigation menu and adds a class to the `<li>` item when the item `url_title` is equal to the current URL `segment_1`.  If the menu is then later retrieved from cache by a template where the URL contains a different `segment_1`, the highlight will appear against the 'wrong' item.  If the same construct was cached using normal tag caching this problem would not occur.

**Comment by robsonsobral** [comment]
Man, I know how your example works, I know what your code does. What I don't understood is how it applies to the case. Please, don't be condescending.

Yes, I've fingers, but that doesn't mean I shouldn't be allowed to use a hammer. It's sad. My suggestion is an easier version of an SSI; not something new and complicated. Neither, the case for leaking data is new: this can already be done today. I've a lot of use cases for it over my projects. For example, a menu which uses 2 `exp:channel:categories` and run again and again at every page. Today, this website has 390 categories and 1523 entries.

The most expensive feature of EECMS is the `exp:channel`. It uses a lot of queries and calls a lot of libraries. Using the project I'm working on as an example and only one `exp:channel:category_archive` tag cached, it saved 5 queries.

```
<!--
+-------------------------+----------------------------------------------+
| Queries:                |   57
| Memory Used:            |   10.4MB
| Date and time of parse: |   2021 07 27 10:00:26
| App build:              |   20210521
| App version:            |   6.0.6
+-------------------------+----------------------------------------------+
-->
```

```
<!--
+-------------------------+----------------------------------------------+
| Queries:                |   52
| Memory Used:            |   10.42MB
| Date and time of parse: |   2021 07 27 10:02:07
| App build:              |   20210521
| App version:            |   6.0.6
+-------------------------+----------------------------------------------+
-->
```

On a `exp:channel:entries` only, at the same page, it saved 8.

```
<!--
+-------------------------+----------------------------------------------+
| Queries:                |   53
| Memory Used:            |   10.42MB
| Date and time of parse: |   2021 07 27 10:08:41
| App build:              |   20210521
| App version:            |   6.0.6
+-------------------------+----------------------------------------------+
-->
```

```
<!--
+-------------------------+----------------------------------------------+
| Queries:                |   45
| Memory Used:            |   10.29MB
| Date and time of parse: |   2021 07 27 10:13:52
| App build:              |   20210521
| App version:            |   6.0.6
+-------------------------+----------------------------------------------+
-->
```

So, there are cases for it, there are benefits and there aren't available tools in the core to do the same.

I'm sorry I took your time for something I wasn't capable of to explain clearly. Good morning.

**Comment by jcogs-design** [comment]
No intention to be condescending.
I don't really understand why this is so hard.
I have a couple of concerns about your suggestion: the 'random' content issue, and the lack of clarity about how the alternative proposed offers advantages over regular tag caching (other than perhaps saving a bit of disk space).
I have tried hard to clarify these points in response to your observations, but do not appear to have been successful.
I am not sure there is anything further to clarify: let's let others read these comments as and when and decide what they want to do etc.

**Comment by intoeetive** [comment]
In general, I tend to like the @robsonsobral 's idea.

I do share some of concerns that @jcogs-design has (in particular, related to uniqueness of cache key and cache clearing/breaking).

However this seems to be fairly easy to create proof-of-concept code and then we can test it in various cases to see how valid are those concerns. FWIW, I think the most time consuming here would be not actual code, but the testing.

**Comment by robsonsobral** [comment]
I can help a little with the testing, as I'm working on a huge site. While on development and staging environment only, I can test and map situations to create automatic tests.

Let's see what happens.

(Maybe I can even prove the reason for that! 😉 )

**Comment by robsonsobral** [comment]
I've read all discussion again and I've found a possible point which could generate support requests: different behavior for different tags, as some of them are URL dependent and others don't.

To make that more explicit, I suggest a parameter to override the cache key (at least apparently). The real key would still take the parameters and content into account, to prevent conflicts by mistake.

```html
{exp:module:one cache="yes" refresh="30" cache_key="default_site:sidebar"}
content
{/exp:module:one}
```

```html
{exp:module:one cache="yes" refresh="10" cache_key="default_site:sidebar"}
content
{/exp:module:one}
```

```html
{exp:module:one cache="yes" refresh="30" cache_key="default_site:sidebar"}
different content
{/exp:module:one}
```

**Comment by intoeetive** [comment]
It is now possible to apply `cache_prefix="global"` parameter (as well as custom `cache_prefix` values) which I believe covers what has been discussed here
https://docs.expressionengine.com/latest/channels/entries.html#cache-refresh-cache_prefix
