### ISSUE TITLE
Fluid field conditional doesn't work on live preview

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#13]
It's always false and the content doesn't show, even when editing an entry.

It does work on the frontend.

example code where le-resources is a fluid field:

```
{if le-resources}
Show me if the fluid field le-resources has content
{/if}
```

**Comment by kevincupp** [comment]
I don't think `{if fluid_field}` conditionals are working right at all. This person must have one of their fields set to be searchable, because that seems to be the only way it would work on the front end normally. Anyway, I've got it working as it should but running into other live preview oddities, trying to get those nicked.
