### ISSUE TITLE
Problems with User Logout on EE6 Control Panel

### ISSUE THREAD

**Issue by maposch** [ExpressionEngine/ExpressionEngine#1314]
Hello!

We actually have a Problem on EE6 with the User Logout Function (EE6 Control Panel). Our Site-Users on our productive Instance cant log out - no matter which browser is curent used. Our users always stays "logged in".

Do you know this Problem? 

We ask for a short answer!

Thanks & best regards!
Markus Posch

**Comment by robinsowell** [comment]
I can't actually replicate, but I did run into another user who had the same issue.  Turns out they had used the 'guest' default role and changed the settings so that they had access to the control panel.  But guests are assumed by the system to be logged out users.  It caused some weird issues, including an inability for members in that role to logout of the control panel.

I'd check that- role id 3 should be reserved for 'guests'- aka logged our visitors.
