### ISSUE TITLE
Live Preview renders some urls with BBCode instead of HTML

### ISSUE THREAD

**Issue by creativearc-paul** [ExpressionEngine/ExpressionEngine#142]
**Description of the problem**
When attempting a Live Preview, the main layout seems to render, but particular content with all-caps markup that isn't rendered properly. I thought it only affected Wygwam entries, but found the same thing happened on simpler pages.

**How To Reproduce**
Any LivePreview action on a channel entry.

**Screenshots / Videos / Template Code**

Redacted screenshot:

https://www.dropbox.com/s/457rvxc5eoqawza/2019-03-01_16-21-00.png?dl=0

That screenshot shows how LivePreview renders. On the frontend, that is a nicely organized list of links.

**Environment Details:**
EE 5.1.3

**Additional context**

The only clue I thought I'd share is this site uses layouts/embedded templates a bit more than our norm, but nothing outlandish.

**Comment by derekjones** [comment]
Case-sensitivity doesn't seem to be involved, but what field type is this content in? I believe this is related to a known issue (that also affects Wygwam).

**Comment by creativearc-paul** [comment]
In this case, the footer links are stored in a Grid that contains Wygwam fields for columns.

**Comment by derekjones** [comment]
Ok, confirms it's the same issue then. This is the first public issue for it, though, I believe, so thank you!

**Comment by kevincupp** [comment]
This is happening because of this code:

https://github.com/ExpressionEngine/ExpressionEngine/blob/ad4175a9f597b8e6f4d3d52ef70032bc97c1f9dc/system/ee/legacy/libraries/Typography.php#L685-L694

Live Preview is technically a `CP` request, so it's turning all the links into BBCode. Just below that, it gets decoded again, but only if the current instance of Typography's `text_format` setting is NOT set to `none`. So, if you have a Textarea or something, or if you're in Wygwam, and your field's format is set to `none`, all of your links will look like `[url="http://google.com"]Google[/url]` on the front-end.

The idea we had internally to fix this is to make Live Preview an action request, something like `?ACT=preview` and maybe have it masquerade as a `PAGE` request, that way everything behaves more normally, and gives us room to iterate to make shareable previews so you're not sharing a CP URL.

It might be a change best saved for 6.0 since who knows what kind of reliance some add-ons have on analyzing `REQ` or CP URL segments to branch their logic.

**Comment by intoeetive** [comment]
Is there any update on this issue? We have experienced the same with EE 5.2.6 and Wygwam

**Comment by derekjones** [comment]
Yes, it was determined to change its request type as @kevincupp alludes to above, since the proper fix for it will be a potentially breaking change. Otherwise there is potential for exposure of your control panel URL in referer logs.

**Comment by intoeetive** [comment]
Live Preview has been changed to be ACTION request in EE6, therefore this issue is not relevant anymore
