### ISSUE TITLE
Member Roles (#) - Count of members made more accurate or descriptive

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#1467]
EE Version 6.1.4
PHP Version 7.3.30

Right now, the (#) displayed after a Role only reflects how many members have that role assigned as their Primary Role. 

This feels a little deceiving and dangerous, as I could be tempted to delete a Role, not realizing it is a secondary role assigned to a plethora of members. 

I would rather have the (#) reflect both Primary and Secondary role assignments, or have it broken out. For example: 
> Role Name (# primary, # additional)
or
> Role Name (# *star icon, #)

See example screenshots where the Staff Portal role reflects 0 members, but in reality, there are 5.

![Screen Shot 2021-10-20 at 11 04 22 AM](https://user-images.githubusercontent.com/20441129/138148280-073d83d4-78bc-4776-a42d-70fdab84e87c.jpeg)

![Screen Shot 2021-10-20 at 11 04 11 AM](https://user-images.githubusercontent.com/20441129/138148229-0ace8b20-f620-48f0-bae0-1099309f7b84.jpeg)

**Comment by PaulBaileyAtChan** [comment]
A couple of additions to this.

- The misleading member count shown after each role is especially dangerous because there's no check or prompt for existing secondary users if a role is deleted. The user is asked to confirm the deletion, but there's no indication of whether there are existing secondary users who would lose that role. (Including a prompt like that with the deletion confirmation would be a very good thing.)
- Also, in EE<=5, the member count shown after each role acted as a link to display a list of those members, which was useful. In EE6, that seems to be broken. It does seem to work as a link, but just lists all users, not users with that role attached. This looks like a bug to me, because linking to all users from here has no practical use.

Honestly, there's a lot that could be tightened up here. Not totally sure the new role management interface was properly tested.

**Comment by intoeetive** [comment]
@ajohnson what are your thoughts on this?

**Comment by ajohnson** [comment]
@intoeetive @mcfarlandonline @PaulBaileyAtChan All great points!

It looks like a fix has since been implemented for the link to display a list of members. Good deal.

The quickest improvement to the count display would be to simply make the count reflect the _combined_ number of primary _and_ additional within the _single_ count number. Clicking on that count number links to a list of all members who have that role assigned as either primary or additional (the link seems to be working properly after the recent fix).

But _breaking up_ the count into primary vs. additional numbers brings up some questions regarding how the link(s) would behave (e.g. do we create separate links for primary vs. additional, and if so, how will the capabilities of the current "role" filter handle this distinction, etc.). Or do we just combine the primary/additional numbers into a single link (definitely the simplest approach). A few other things need to be considered as well.

So for the sake of eliminating the danger here as quickly as possible I recommend starting with making the count reflect the _combined_ number of primary _and_ additional within the _single_ count number. And keep the fixed link functioning as-is.

Thanks (and feel free to push back with other thoughts)!

**Comment by mcfarlandonline** [comment]
I think combining the count is a great solution and a much safer indicator than what's currently represented. Thanks!

**Comment by PaulBaileyAtChan** [comment]
Would the suggested fix include prompting the user on attempting to delete a role that there are either primary _or secondary_ users with that role assigned? It should.

**Comment by ajohnson** [comment]
@PaulBaileyAtChan I agree that would be best. It could be as simple as adding that info after the existing role name(s) in the delete confirmation modal like so:
<img width="584" alt="Screen Shot 2021-11-10 at 1 50 20 PM" src="https://user-images.githubusercontent.com/194579/141175051-88cdb70d-9235-4deb-80f0-d17c87027239.png">

@intoeetive Not sure how complex that is to pull off from a back end perspective.

**Comment by intoeetive** [comment]
@ajohnson so do I understand correctly that the suggestion is to show the number of members **combined** when in the list view, however when performing delete attempt (maybe also somewhere on role details page?) we should separately number of primary members and also additional number (would that include members assigned via role groups? or you think we should list those separately as well?)

**Comment by ajohnson** [comment]
@intoeetive You are correct: **combined** in the list view, and **broken out** in the delete confirmation modal.

And regarding members assigned via role groups, those assignments would be included in both the combined number, and within the broken out primary/additional numbers. But would not require a separate number.

For example, when a member is currently assigned to one or more roles via a role group, those roles are displayed within the "Roles" column on the main Members table list. But they aren't distinguished from other roles that were assigned directly (i.e. not via a role group).

So the "method" of role assignment isn't as critical as the roles themselves when displaying these numbers.

**Comment by mcfarlandonline** [comment]
The combined-count of members assigned to roles still seems glitchy in v6.3.2, (example below). 

Anyone else? 

<img width="441" alt="Screen Shot 2022-04-20 at 1 56 04 PM" src="https://user-images.githubusercontent.com/20441129/164322526-dd45cdae-f6bc-4d4a-88a2-610a8e42f95f.png">

**Comment by PaulBaileyAtChan** [comment]
+1 Yep, not working for me in EE6.3.2. I'm getting all zeroes. I've been away from EE6 for a while, so I've no idea if this was working earlier and then not, but it seems glitchy now. FWIW, this is a site that was upgraded from EE5, with all of the members & roles pulled across.

**Comment by PaulBaileyAtChan** [comment]
I'm afraid I'm still seeing issues in 6.3.4. Results of some quick testing:

I created a new member role, "Silly Role", and assigned two members to this role (in addition to some other, secondary roles). Listing this role in "All Members" correctly shows both members:

<img width="839" alt="Screen Shot 2022-05-09 at 1 40 49 PM" src="https://user-images.githubusercontent.com/46760375/167497167-b4ae035e-0626-4852-ba06-9fba559f97fa.png">

But on the "All Roles" page, this role only shows "(1)" member:

<img width="789" alt="Screen Shot 2022-05-09 at 1 41 24 PM" src="https://user-images.githubusercontent.com/46760375/167497350-0faccbbc-8f8f-42c7-905d-ac64222a96bd.png">

Additionally, the "Show" drop-down on the "All Members" page gives "All 4 members", which is also incorrect:

<img width="840" alt="Screen Shot 2022-05-09 at 1 41 08 PM" src="https://user-images.githubusercontent.com/46760375/167497531-bf336e66-7b82-408a-a5f5-77cd5726e4a5.png">

All of this really needs to be tested a lot more thoroughly.
