### ISSUE TITLE
one click updater not working EE 6.0.6

### ISSUE THREAD

**Issue by Fred2341** [ExpressionEngine/ExpressionEngine#1490]
Hi there

on some websites the one click updater (from EE 6.0.6) is not working. Is there a general reason why this is the case?
I suppose the obvious solution is a manual update, but I would prefer a solution to the one click version.

Regards

Fred

**Comment by intoeetive** [comment]
One of the common issues people experice is when theme folder path is pointing to wrong directory, or missing slash. Can you check that?

**Comment by Fred2341** [comment]
Thanks for your quick response, Yuri.

The path setting seem to be OK. See attached image.

Regards
Fred Geiger
M: 06 1092 8658

**Comment by TomJaeger** [comment]
Quick few thoughts / notes on this one.

In 6.1.0 -> 6.1.5 we've added several items to 1 click updater to be smoother and display more information.  One of the difficulties with it, is that you have to upgrade (with the old 1 click updater) to get the new one.

In addition to this, we also made some server certificate changes today that resolved issues that some people we're running into.  If you click upgrade again, and it goes through it was likely fixed by this change.

If it doesn't go through, I'd recommend looking at your network inspector, and look at the request response specifically.  It will likely give more info as they why it failed.   That would help us better determine best next steps.

**Comment by Fred2341** [comment]
Hi Tom

I looked at the error log after the upgrade, but there was nothing.
At fiets I get following error message during upgrade:


After removing the updater folder:


But when re-opening the CP:



Can I ignore this?

Regards

Fred Geiger
M: 06 1092 8658

**Comment by Fred2341** [comment]
I subsequently changed the config.php file to show version 6.1.5, Is that sufficient or can I expect more trouble?

Regards

Fred Geiger
M: 06 1092 8658

**Comment by intoeetive** [comment]
If you just changed the version from 6.0.6 to 6.1.5 then you might get some issues, as the update included several database changes. You would be better by downloading the release and updating manually

**Comment by Fred2341** [comment]
Thanks for the info, Yuri.

Is it still possible to update manually as the “system” thinks I already have version 6.1.5?

How would I see the “database issues”? 

Regards


Fred Geiger
M: 06 1092 8658

**Comment by intoeetive** [comment]
You can just set your version in config.php to whatever you had prior to update (6.0.6?), ensure /system/installer/ folder is present and visit the CP. This will trigger the update wizard which will run all necessary updates

**Comment by Fred2341** [comment]
One final question to this, Yuri.

Is it indeed sufficient to upload only the installer folder, and not the other folders/files?

Regards

Fred Geiger
M: 06 1092 8658

**Comment by intoeetive** [comment]
Only if you are sure all other files are updated. Otherwise I strongly recommend replacing all files, after making backup

**Comment by Fred2341** [comment]
Hi, the upgrade to 6.1.5 worked well with the installer folder uploaded and config.php changed back to the previous version.
However, the one click upgrade to 6.1.6 again failed, with the same error: 

Oops, looks like the updater couldn't complete. We stopped on Preflight check.

This is becoming a pain in the butt. How to prevent this?
Regards
Fred

**Comment by Fred2341** [comment]
It now works on all websites.
