### ISSUE TITLE
Error when trying to upgrade to EE6

### ISSUE THREAD

**Issue by joshconner** [ExpressionEngine/ExpressionEngine#1519]
Attempting to upgrade from EE 5.1.3 to EE 6.1.5. I've attempted to upgrade this site multiple times and in different environments (MAMP Pro and staging server). Each time, the installer bombs out when attempting to go to 5.4.2 to 6.0 on the upgrade screen. It returns a 500 error. If I visit the upgrade page again, it will continue the upgrade process and walk through the versions of 6 until it stops on 6.1.5. But then the issue is the site is broke. Both the front-end and the login page report the same error:

Error Caught
Call to a member function getValues() on null
ee/legacy/libraries/Session.php:524

PHP version 7.4.21 and 7.1.33.

I've provided screenshots, hopefully they'll help.

<img width="703" alt="Screen Shot 2021-10-31 at 11 52 21 PM" src="https://user-images.githubusercontent.com/479358/139620435-68ecb134-9a67-4a32-b864-54ce34909df2.png">
<img width="1210" alt="Screen Shot 2021-10-31 at 11 55 29 PM" src="https://user-images.githubusercontent.com/479358/139620437-8579d231-f9a9-48b8-a355-e952ba90345d.png">

**Comment by robinsowell** [comment]
So that error happens after you restart.  When it fails, it actually stops on a 500 error and no debug available?

Hrm- is the staging server accessible and could we get ftp and cp login for it?  If so, hit me at support@expressionengine.com and I'll dig.  If not, I can walk you through some places to poke.
