### ISSUE TITLE
Using the replace modifier on a category_name tag and it's causing errors on front-end and incorrect output

### ISSUE THREAD

**Issue by 5BYFIVE** [ExpressionEngine/ExpressionEngine#1527]
EE 6.1.5
PHP Version 7.4.3

Using the replace modifier on a category_name tag and it's causing errors on front-end and incorrect output. Recently upgraded to EE 6.1.5, but not sure if this was happening before that. Client hadn't complained until after the update.

```
{categories}{category_name:replace regex='yes' find='/(st\.) (louis)/i' replace='$1&nbsp;$2'}{/categories}
```
![Screen Shot 2021-11-02 at 8 40 34 AM](https://user-images.githubusercontent.com/31897342/139863773-a1b15c11-ced1-4f5f-984b-00df97da0d19.png)
![Screen Shot 2021-11-02 at 8 40 47 AM](https://user-images.githubusercontent.com/31897342/139863799-2b5da253-f5ef-4f2d-80ff-5e032c0315f7.png)

**Comment by intoeetive** [comment]
The errors are pointing to the file module, however the code you posted is only for categories.

Are you able to see the errors if you use JUST that code @5BYFIVE ?

If not, what would be the minimal required code we could use to replicate the problem locally?

**Comment by 5BYFIVE** [comment]
I stripped a template down to the following...This first one works and outputs the category names correctly with no errors...

`
			{exp:channel:entries channel="general_pages" disable="categories|member_data|category_fields|pagination" limit="1" entry_id="332"}
			{exp:channel:categories style="linear" show_empty="no" category_group="2"}
			{if count == "1"}
			<ul class="cat-filter">
			{/if}
				<li>
					<a href="/news-and-media/newsletter-archive?cat={category_id}"{if "{exp:stash:get dynamic='yes' name='cat'}" == "{category_id}"} class="active"{/if}>{category_name}</a>
				</li>
			{if count == total_results}
			</ul>
			{/if}
			{/exp:channel:categories}
			{/exp:channel:entries}
`

![Screen Shot 2021-11-09 at 10 47 31 AM](https://user-images.githubusercontent.com/31897342/140967807-634d7f96-db09-4b18-9b9e-4f800e5e90a4.png)

This next one with the modifier shows the errors and the output of the category names is cut off after the first letter....

`			{exp:channel:entries channel="general_pages" disable="categories|member_data|category_fields|pagination" limit="1" entry_id="332"}
			{exp:channel:categories style="linear" show_empty="no" category_group="2"}
			{if count == "1"}
			<ul class="cat-filter">
			{/if}
				<li>
					<a href="/news-and-media/newsletter-archive?cat={category_id}"{if "{exp:stash:get dynamic='yes' name='cat'}" == "{category_id}"} class="active"{/if}>{category_name:replace regex='yes' find='/(st\.) (louis)/i' replace='$1&nbsp;$2'}</a>
				</li>
			{if count == total_results}
			</ul>
			{/if}
			{/exp:channel:categories}
			{/exp:channel:entries}
`
![Screen Shot 2021-11-09 at 10 47 42 AM](https://user-images.githubusercontent.com/31897342/140967877-ec9afef7-7875-4903-be52-a12e71fad219.png)

**Comment by Zignature** [comment]
I'm having the exact same error on EE6.1.6 (just updated from EE6.0.3)

![image](https://user-images.githubusercontent.com/4068757/144328117-32538bd8-41f1-4ac2-adf8-56aa3d1d9232.png)

And the category names I'd like to display are cut off at the first character:
![image](https://user-images.githubusercontent.com/4068757/144328728-59ce794d-d73c-4418-b299-767c7cebc4da.png)

 It's supposed to be:
![image](https://user-images.githubusercontent.com/4068757/144328788-74b85f9a-148b-49fa-a258-250e0b745a18.png)


The error is caused by a `limit` modifier on a `{category_name}` tag.
My tag looks like this: `{category_name:limit characters='80' end_char="&#8230;"}`.
When I remove the `limit` modifier and its parameters, everything is fine.

My error points to a different line number though. Line 631 instead of Line 687.
