### ISSUE TITLE
Add phpdotenv to ExpressionEngine Core

### ISSUE THREAD

**Issue by jaredchesebro** [ExpressionEngine/ExpressionEngine#1565]
**Is your feature request related to a problem? Please describe.**
As time goes on the `config.php` file gets more and more complicated. Every setting under the sun can be added and changed there. The problem is that some of the values are considered sensitive or security risks. Some specific examples are the encryption key, session encryption key, and now the site license key. It would be nice to store any sensitive values in a `.env` file so we can safely commit our `config.php`. Because we can't commit our `config.php` we have to always keep track of it via some other backup method.

**Describe the solution you'd like**
I would like phpdotenv to be included in ExpressionEngine core so that we can set any config values we want in a `.env` file which can be ignored in our `.gitignore` file. I would also like ExpressionEngine to populate any errors necessary for proper configuration when `.env` and `config.php` are missing required values. If a `.env` is present and has conflicting values compared to `config.php` then `.env` values should take precedent.

**Describe alternatives you've considered**
We have included phpdotenv in our `config.php` but are having trouble implementing an error reporting strategy that is helpful when first adding our `.env` file.

**Teachability, Documentation, Adoption, Migration Strategy**
Because other CMS include phpdotenv I think this will be a welcome feature and many EE developers will already know how to utilize it.

**Comment by matthewjohns0n** [comment]
I agree that something like this is a needed feature in EE. We have talked about this internally several times and it's definitely on our radar. 

Currently, there are a few security concerns we have about adding phpdotenv:

Right now, ExpressionEngine can be installed in a variety of ways. Despite the [Best Practices](https://docs.expressionengine.com/latest/installation/best-practices.html#moving-the-system-directory-above-webroot) in the docs, there are many sites that have the `system` folder in the webroot. This is a problem because any file in the webroot can be requested and the web server will attempt to serve it. If the file is a PHP file, PHP will execute the code in the file, and not actually return the file contents. However, if there is no webserver rule denying files that start with `.`, apache/nginx will return the contents of that file. In this case, you could just visit `example.com/system/user/.env` and see the contents of the .env file. 

From what I understand, not all web servers default to denying files starting with `.`, and we can't introduce or force webserver rules.

Because of this, we're weary to include this in the core since there would be a potential for some sites to have their secrets exposed. Some PHP-based frameworks are structured in a way where it is impossible to reach the .env file, but ExpressionEngine allows more flexibility in this regard.

An alternative that we have thrown around is to use a `.env.php` file, which PHP would parse and not return the contents. 

I also wanted to point out that we (EEHarbor) do have the add-on [Manifest](https://github.com/EEHarbor/Manifest/tree/ee3ee4) that does exactly this. This is an add-on we have used on many sites to solve this exact problem. We intentionally do not promote it to everyone though, due to the concern regarding sites that are running with their `system` folder in the webroot. Despite the fact that it hasn't been updated in a long time, it does work in EE6.

**Comment by jaredchesebro** [comment]
@matthewjohns0n Thank you for those thoughts. I think the more that our team has broadened our developer skill sets the more this becomes a pain point. We are starting to use CI/CD tools more to improve our workflow and the config.php is real PITA. 

Currently we have our own custom phpdotenv setup but would probably consider switching to Manifest depending on how easy it is to keep phpdotenv up to date within the addon. After I run composer update is there any other modifications I'll have to make to the addon to keep things working? Seems like the version contained in the addon is a bit old.

**UPDATE:** I forked Manifest and updated phpdotenv to the latest version. It did take a little bit of modifying the load() function in mod.manifest.php to get things working as I wanted them. Here's what I came up with: https://github.com/mc2designgroupinc/Manifest/tree/ee6

**Comment by robsonsobral** [comment]
Couldn't move Manifest within ExpressionEngine company profile be the first step into this path?

There's a lot of "essential" addons all over Github and we need to keep them update and the community engaged.

**Comment by matthewjohns0n** [comment]
> **UPDATE:** I forked Manifest and updated phpdotenv to the latest version. It did take a little bit of modifying the load() function in mod.manifest.php to get things working as I wanted them. Here's what I came up with: https://github.com/mc2designgroupinc/Manifest/tree/ee6

Thanks for updating that - although that repo is set to private and I don't have access to see it.

**Comment by matthewjohns0n** [comment]
> Couldn't move Manifest within ExpressionEngine company profile be the first step into this path?

That might be a good next step - although ultimately a question for @TomJaeger.

**Comment by robsonsobral** [comment]
Of course, @TomJaeger agrees! No doubt on that! 🙏

**Comment by jaredchesebro** [comment]
> > **UPDATE:** I forked Manifest and updated phpdotenv to the latest version. It did take a little bit of modifying the load() function in mod.manifest.php to get things working as I wanted them. Here's what I came up with: https://github.com/mc2designgroupinc/Manifest/tree/ee6
> 
> Thanks for updating that - although that repo is set to private and I don't have access to see it.

@matthewjohns0n Sorry, I found some issues with getenv() fallback so I set the repo to private while I figured things out. Should be available now: https://github.com/mc2designgroupinc/Manifest/tree/ee6

Things are working pretty much as I'd expect them to. It would also be really helpful to start versioning and creating releases for the addon to make it easy to stay up to date.

Also, I agree with @robinsowell if the answer to this feature request is "Use Manifest" then Manifest should be actively developed and easily accessible.

**Comment by intoeetive** [comment]
Support for `.env` files have been included with ExpressionEngine 7: https://docs.expressionengine.com/latest/advanced-usage/env-support.html#env-file-support
