### ISSUE TITLE
Shared Form View: 'short-text' type inputs throws E-Notice if 'label' parameter not specified

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1569]
If you use the `short-text` input option in the [Shared Form View](https://docs.expressionengine.com/latest/development/shared-form-view.html#available-field-input-types) the resulting CP page will include 'E Notice' errors unless an additional parameter called "label" is defined for that field.

The 'label' parameter is not documented in the Shared Form View text, but when added to the short-text field definition adds some text below the input area.  This attribute only appears to be defined for the `short-text` and `select` input types - critically it is not defined for the regular `text` input option. It is not clear why.

The code in question is the fragment that processes the shared form view element in the file [ee/ExpressionEngine/View/_shared/form/field.php](https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/View/_shared/form/field.php) from line 70
```
<?php break;
    // no break
case 'short-text': ?>
	<label class="flex-input <?=$class?>">
		<input type="text" name="<?=$field_name?>" value="<?=$value?>"<?=$attrs?>>
		<span class="label-txt"><?=lang($field['label'])?></span>
	</label>
```
Probably the easiest fix is to make inclusion of the `<span>` line conditional on `isset($field['label'])`

**Comment by matthewjohns0n** [comment]
Thanks for reporting this, I was able to replicate this. I agree - it should either be documented that `label` is required, or it should just not be required. 

I prefer not requiring it, since that seems to be consistent with the current docs, and in my mind, there's no reason why it should be required. I looked at examples from the core, and a lot of them leave `label` as an empty string already.
