### ISSUE TITLE
Field Instructions for Entry Title

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1790]
I could really use Field Instructions for the Entry Title. Why is it the only field that don't have it?

**Comment by shbchk** [comment]
Maybe, ability to add (or override, in case it exist in field settings) Field Instructions can be added in Publish Layouts?

**Comment by shbchk** [comment]
Like this:
![ssss](https://user-images.githubusercontent.com/12234507/152645022-1ab667bd-fa84-4628-960d-c7cdeb72042e.png)

**Comment by robsonsobral** [comment]
We can already customize the title field per channel. To customize its instructions isn't a bad idea.

This looks like a feature for a PR.

**Comment by blue-dreamer** [comment]
Can we add the ability to add title overrides and instructions to all core fields, Entry/Expiration date, Statuses etc, This would be handy to describe what those fields do, e.g. if I'm using Entry/Expiration dates for events it's handy for less savvy clients to understand what each field is for.

And while we're talking field instructions it'd be super handy to add a instructions for category groups as well.

**Comment by tboelskifte** [comment]
Also, if we could add instructions to the Title field, we could avoid this:

https://www.dropbox.com/s/coa6exw9wieoswq/ee-title-field-misalignment.jpg

This of course only happens when changing the layout for a channel, to have the Title and URL Title on the same line. But for us with medium-strength OCD, it's an abomination ;-)
