### ISSUE TITLE
Status changes to none (choose wisely) when saving some channel data

### ISSUE THREAD

**Issue by Fred2341** [ExpressionEngine/ExpressionEngine#1877]
In two of the channels, saving existing and modified data changes the status from 'open' to none (choose wisely). In all of the other channes everything works fines.
This is also the website that fails the single point upgrade.

**Comment by intoeetive** [comment]
I believe this is the same issue as https://github.com/ExpressionEngine/ExpressionEngine/issues/477, so closing as duplicate.

In short, the situation might occur when member has permissions on the channel, but does not have permission to the status that the entry has. While this might be intentional, we probably need to show them a warning that the current status might be lost.
