### ISSUE TITLE
Parens in custom field name exhibits odd behavior

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#1931]
Found a strange and very specific behavior where creating a new custom field with the name of `File (basic)` results in the name actually being saved as `File &#9001;basic&#9002;`. I tried other combinations of wrapping text in parens, but it seems very oddly specific to the word file and basic.

I'm running 6.3.0dp btw. I have not tested this in 6.2.x

<img width="385" alt="Screen Shot 2022-03-26 at 3 41 39 PM" src="https://user-images.githubusercontent.com/53965/160256447-dd93918a-cb95-48fe-beaa-950bb50fcad7.png">

**Comment by intoeetive** [comment]
The reason for this is XSS check. Since `file` is also the name of PHP function that reads the file, the system is making sure the field name is not something that could be used for exploit, when used in combination with some other code.

Somewhat unexpected for end user, but that's the limitation we can't remove right now
