### ISSUE TITLE
Developer menu in CP confusing for ordinary users?

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#195]
**Is your feature request related to a problem? Please describe.**
When non super admin control panel users have access to modules it activates the "Developer" menu. The word "developer" can be confusing - I've just upgraded a site from EE2>EE5 and the client mentioned it.

**Describe the solution you'd like**
Either:
1. Rename the menu link name to something more logical like "Settings", or similar.
2. A method to allow access to specified addons without the Developer menu, use menu manager links instead.

**Comment by jmathias** [comment]
Hi Rob, thanks for the feedback, we appreciate it.

The developer menu is named as such, because it contains links to items that are used primarily by site builders (developers). We only hide the button when the logged in user doesn't have permissions for something that appears in that menu. We recommend only giving a user permissions to things you trust them to use.

> Rename the menu link name to something more logical like "Settings", or similar.

We already have a settings menu item, to the right of the developer menu.

> A method to allow access to specified addons without the Developer menu, use menu manager links instead.

You are already able to do this, to help give your clients a shortcut to any add-on then may need to access. The developer menu will still be visible, and a user with permissions will be able to access the menu.

It sounds like what would be most helpful would be to move the add-ons manager link out of the developer menu, so that when a customer has permissions for add-ons, the developer menu doesn't need to show. This removes confusion, and gives the non-savvy user a way to access the add-ons without needing additional training.

**Comment by blue-dreamer** [comment]
Yes I totally get the need for the Developer menu, and of coyrse "Settings" already exists - I was really searching for another word to describe things for non super admins.

In this case the client needs access to various addons such as Low Variables and Store which of course is all above board for members that need to access them.

The ability to access allowed addons outside of the Developer menu would be the way forward as you say. Right now the Developer menu has to be enabled for the clients CP member group so they can access necessary addons.

Ideally we need another option in Member group settings so we can select the menu types available: 

Access developer menu N/Y
- enables access to Channels, Fields, Templates, Utilities, Logs

Access addons menu N/Y
- enables access to Addons where permission is granted

That raises a related issue. I have several clients who regularly need to access categories, either to add new or modify data in category fields. Right now they can only be accessed when editing an entry or via the Developer menu, both are a bit counter intuitive. Having the ability to access categories outside of the Developer menu with appropriate permissions would be useful.

**Comment by jmathias** [comment]
Thanks Rob, I'll definitely work through some ideas to see how to best solve this issue.

> Ideally we need another option in Member group settings so we can select the menu types available

We don't offer direct menu settings, we have the top-level menu items display based on what the user has permissions to. This prevents site builders from accidentally turning off a menu that the user has access to. In other words the permissions are based on what they can access, not what is in the menu item's sub-menu.

> That raises a related issue. I have several clients who regularly need to access categories, either to add new or modify data in category fields. Right now they can only be accessed when editing an entry or via the Developer menu, both are a bit counter intuitive. Having the ability to access categories outside of the Developer menu with appropriate permissions would be useful.

This would be a great use case for a custom menu item. We can't have everything be a top level menu item, which is why we created the custom menu bar, so that site builders could give their clients a custom menu set, that is relative to their site.

**Comment by blue-dreamer** [comment]
Good points about direct menu settings. So long as we can bypass the need for the Developer menu for stuff that clients need to access (addons/categories), custom menu items would be ideal - we can then offer a drop down menu for links or separate links as needed.

**Comment by Jordan-Ellis** [comment]
Hi Rob!

The add-on and category links have been moved out of the developer menu in EE6! They now reside directly in the sidebar if the member has permission to access it.
