### ISSUE TITLE
Basic member registration tools

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#196]
I'm creating member profile editing screens, so that ecommerce customers can edit their contact details, billing/delivery address, etc.
But I can't find a way to allow customers to create new accounts from scratch.

I know I can use add-ons like User, or Visitor (from EE Harbor), but it seems bizarre that there aren't, at least some basic, member registration tools available, to allow frontend registration forms.

There is an existing Login form which uses this format:
{exp:member:login_form return="site/index"}
  -- login form fields --
{/exp:member:login_form}

So maybe something like this would work?
{exp:member:registration_form return="user/account"}
  -- registation form fields --
{/exp:member:registration_form}

**Comment by derekjones** [comment]
This is planned for the next major version to have more typical and familiar tags for Member management. But ExpressionEngine has always allowed for front-end member tools, via [Member profile templates](https://docs.expressionengine.com/latest/member/index.html#member-profile-templates). It's less flexible because it uses a predefined set of partials and URL triggers (so behaves more like a discussion forum's member pages), but you can use any ExpressionEngine tags within those templates, so full and robust member tools are possible. Just not as friendly and flexible as the rest of ExpressionEngine. But again, 100% agree on what it *should* be, and that's the plan for v6.

**Comment by ic360-com** [comment]
Sounds good - looking forward to that. Thanks a lot.
:-)

**Comment by intoeetive** [comment]
In EE6, you can use https://docs.expressionengine.com/latest/member/registration.html#registration-form-tag

**Comment by ic360-com** [comment]
Looks good, thanks a lot - will give it a go, next time.  :-)
