### ISSUE TITLE
File fieldtype loading error

### ISSUE THREAD

**Issue by ScottAG-KB** [ExpressionEngine/ExpressionEngine#206]
When editing an entry with a fieldtype of file, or file within a grid in combination with other fields, the loading graphic is rendered, javascript errors occur and we are unable to properly modify the entry.  The entry screen functions as intended if the only visible field (in the channel layout) is the file field, and conversely, all other fields work if the file field is hidden.  There are no PHP errors or warnings.   This is occurring on any entry where we have the file fieldtype.

Creating a new set of fields/channel/entry (as below) does the same thing.

**Screenshots / Videos / Template Code**
Screen with error
![image](https://user-images.githubusercontent.com/50633742/57717737-7dfa0580-7641-11e9-8e1b-25fc87805cc1.png)
Network screenshot
![image](https://user-images.githubusercontent.com/50633742/57717921-d6310780-7641-11e9-9287-82fa91e6a9bf.png)
Console screenshot
![image](https://user-images.githubusercontent.com/50633742/57717939-de894280-7641-11e9-8c8e-f962bfa52d27.png)
Screen with only file available in layout - works ok.
![image](https://user-images.githubusercontent.com/50633742/57718190-59eaf400-7642-11e9-95de-cb9e414564be.png)

 - Version: 5.2.2
 - PHP Version 7.3.4
 - MySQL Version 5.6.26
 - OS: Windows server 2012
 - Web Server: IIS 8.0

**Additional context**
We have seen a few entries where mod_security could be an issue, however, we do not have that module installed for IIS.  The syntax error is during the preparation of the date_picker.js in themes/ee/asset/javascript/compressed, however, doubt that is the root cause.  We've removed add-ons (structure, matrix, assets) and even replaced the themes folder with a fresh copy with no change.  Any suggestions are welcome.

**Comment by mcfarlandonline** [comment]
I'm having a similar issue. I'm still in development running on PHP 5.6 (because there's a live copy of EE2 in the same account), but this issue just started. It's only occurring in some channels for me.
![Screen Shot 2019-05-15 at 2 47 06 PM](https://user-images.githubusercontent.com/20441129/57812037-ba506300-7720-11e9-9cc7-5e3adecb55a0.png)

**Comment by CJSweatt** [comment]
I am having the exact same issue where upload fields never fully load.  I would love to get this issue resolved ASAP as this is a time-sensitive project.

![Screenshot 2019-05-18 16 04 03](https://user-images.githubusercontent.com/50816537/57995540-84d8ac00-7a77-11e9-9ba5-43468ac8340c.png)

**Comment by mcfarlandonline** [comment]
Hi @CJSweatt, 
Is this install part of a Multiple Site Manager, by chance? I haven't had a chance to replicate this yet, but we got a temporary fix by re-assigning one of the file field's designated upload file directories in the field's settings and saving. It may also work for non-MSM sites, too.

**Comment by CJSweatt** [comment]
Hi @mcfarlandonline 
I did have MSM enabled, but I ended up disabling it last week since I will not be needing it for this project.  I will try your workaround first.  If that doesn't work, I will try deleting and recreating the upload directories.  This has turned out to be very frustrating.

Thank you!

**Comment by CJSweatt** [comment]
Hi again, @mcfarlandonline,

It's the strangest thing!  I haven't been able to make the changes I talked about in the previous post until today.  When I logged in, all file upload fields were working again.

Again, I have made NO changes to the site or the server environment.  So strange!

![Screenshot 2019-05-21 19 16 46](https://user-images.githubusercontent.com/50816537/58142809-5dabe700-7bfd-11e9-8ec2-b564a255d86f.png)

**Comment by robinsowell** [comment]
My first thought is a mod_security issue loading some of the javascript combo_load files.

Check the network tab, see if you've got any scripts not loading on a page where you have the issue.

**Comment by BridgingUnit** [comment]
@mcfarlandonline @CJSweatt,

Think your issue likely to be related to [this](https://github.com/ExpressionEngine/ExpressionEngine/issues/206#issuecomment-492836878)

I've just run into similar and pretty much got same error messages as you @mcfarlandonline. Also on MSM site. For me primary site has File Upload Pref (which EE sets per site) referenced from a File and File Grid fields which then shared with secondary site. But Allowed Directory setting within the secondary site is missing, because File Upload Pref of the primary site isn't available to the secondary site. 

Problem with your fix though (if I understood correctly) is that changing setting in a shared field within the secondary site to a File Upload Pref available within it will at the same time break the association within the primary for that Field too.

**Comment by intoeetive** [comment]
Closing this out as EE5 issue. EE6 and 7 got a lot of updates for relevant scripts, so this specific GitHub issue would not be relevant for supported EE versions.
