### ISSUE TITLE
EE2 to EE6 Upgrade Breaking Member Consent Page

### ISSUE THREAD

**Issue by erinathop** [ExpressionEngine/ExpressionEngine#2107]
After upgrading from `EE v2.10.1` to `EE v6.3.4` with the single update, we ran into an issue where the Member Consent page would throw errors as noted below. To fix the issue i had to copy the content in `Functionality Cookies -> Request` from another site freshly updated to EE6 into my project site and hit save, which fixed the issue.

Make sure to mention what page you are on, if this is issue in Control Panel - provide the URL (domain name can be removed)
`/system/index.php?/cp/members/profile/consent&id=444`

Add a screenshot. If error backtrace is available, provide it. 
```
Error Caught
Call to a member function format() on null
ee/ExpressionEngine/View/account/consents.php:52

Stack Trace: Please include when reporting this error
#0 system\ee\ExpressionEngine\Service\View\View.php(137): include()
#1 system\ee\ExpressionEngine\Service\View\View.php(106): ExpressionEngine\Service\View\View->parse('D:\\webdev\\EE-De...', Array)
#2 system\ee\legacy\libraries\View.php(40): ExpressionEngine\Service\View\View->render(Array)
#3 system\ee\legacy\libraries\Cp.php(339): View->render('account/consent...', Array, false)
#4 system\ee\ExpressionEngine\Controller\Members\Profile\Consent.php(178): Cp->render('account/consent...', Array)
#5 [internal function]: ExpressionEngine\Controller\Members\Profile\Consent->index()
#6 system\ee\ExpressionEngine\Core\Core.php(255): call_user_func_array(Array, Array)
#7 system\ee\ExpressionEngine\Core\Core.php(111): ExpressionEngine\Core\Core->runController(Array)
#8 system\ee\ExpressionEngine\Boot\boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#9 admin.php(144): require_once('D:\\webdev\\EE-De...')
#9 admin.php(144): require_once('D:\\webdev\\EE-De...')
```
Exactly the same issue as [noted here](https://expressionengine.com/forums/topic/253264/error-consent-settings-bug)

Tell us about your environment (EE version including beta number, PHP/MySQL version, web server, OS etc)
`PHP v7.4.29`
`MariaDB v10.3.28`

**Comment by robinsowell** [comment]
Ah- I replicate.  It looks like the problem is, in the update, it only creates the 'Functional' request and when it does, in exp_version_requests, the consent_request_version_id goes in as NULL.

It does create a matching record in exp_consent_request_versions, but it's not associating that with the record in exp_consent_requests and so basically, it's as if a request version doesn't exist and all that data comes back null and then the date modifier is not happy because we gave it NULL to modify.

<img width="1366" alt="Screen Shot 2022-06-06 at 1 25 00 PM" src="https://user-images.githubusercontent.com/1181219/172213322-3db204ce-a8a9-4378-8942-3cb1d47c6f2c.png">

When you saved it in the consent request settings, it made a new, proper version and associated that and all was well.  But the defaults should go in properly during the upgrade.  We'll get that in for a fix!

**Comment by robinsowell** [comment]
@intoeetive adding on to this- it should have created 2 more consent request records, one for Performance and one for Targeting consents.  If they aren't there, you get that null error in the cp profile when you go to view/edit your consents.  

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1181219/202782084-eabb6456-1515-4cbf-a8b9-b42798742355.png">
