### ISSUE TITLE
Redactor RTE field links default to 'New Tab'

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#2129]
When creating / editing text links in a Redactor RTE field, the Checkbox for "Open link in New Tab" is always selected, regardless.
Can this be defaulted to Off please, unless it's previously been set to On?
Thanks.

**Comment by ic360-com** [comment]
I'm a bit confused about this one - was it fixed? Coz it looks like it's still happening in 7.3.8.

**Comment by intoeetive** [comment]
@ic360-com this might not be "fixed" in a way you want, because this functionality is locked into Redactor 2 engine, which is not being developed anymore (we are considering replacin it with their newer product, but can't name any dates).
What we did though is we added better support for existing [Redactor link configuration settings](https://imperavi.com/redactor/docs/settings/link/#s-linknewtab), so you can set `"linkNewTab": false` in Advanced Configuration JSON if you want to disable this completely.

**Comment by ic360-com** [comment]
Okay I see.
Thanks for confirming... I'll give that linkNewTab variable a go.  :-)

**Comment by ic360-com** [comment]
I've had a play with these settings in the RTE add-on's Advanced Configuration JSON... and found the following to work.
This keeps the "Open link in a new tab" checkbox visible... but switches it Off by default.

`{
    "buttons": [ "html", "format", "bold", "italic", "deleted", "underline", "redo", "undo", "ol", "ul", "indent", "outdent", "sup", "sub", "link", "line" ],
    "plugins": [ "alignment", "rte_definedlinks", "filebrowser", "pages", "inlinestyle", "fontcolor", "limiter", "counter", "properties", "specialchars", "table", "video", "widget", "readmore", "fullscreen" ], 
    "linkNewTab": true,
    "linkTarget": false
}`

This is more inline which how linking the RTE should work, whereby links are internal to the site (same window), but only external (new window) if specially requested.
