### ISSUE TITLE
EE7 Buttons text inside of alerts are difficult to read

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#2201]
Probably a low priority issue, but thought I'd point it out, and this probably affects EE6 too. When a link or button is inside of an alert box I'm not sure they have enough of a contrast ratio on the text, and the orange text inside of the button, especially if the button has `button--primary` or `button--secondary` classes on them, is hard to read.

<img width="147" alt="Screen Shot 2022-08-04 at 1 56 47 PM" src="https://user-images.githubusercontent.com/53965/182943286-6304b486-359c-4179-92e1-dcbd6c24d3a1.png">
<img width="158" alt="Screen Shot 2022-08-04 at 1 56 39 PM" src="https://user-images.githubusercontent.com/53965/182943288-a3e47b6e-4b16-45f8-8865-be5ec9d7bb74.png">

**Comment by Yulyaswan** [comment]
as I can see from EE6 we don't have this issue anymore
EE6
dark theme
<img width="519" alt="alert-for-ee6-dark" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/23382425/b5c55f3f-7d42-4adc-9885-e67a22a59d2a">
light theme
<img width="552" alt="alert-for-ee6-light" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/23382425/617d2c7e-279b-4fbe-b762-1b6cf47af407">
EE7 
light theme
<img width="510" alt="alert-for-ee7" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/23382425/7b66070f-8b08-4284-a974-9eb1bacba08c">
dark theme looks the same as EE6

@litzinger could you please confirm if this problem is still on your side and if yes give more details where to check it
Thank you

**Comment by Yulyaswan** [comment]
I'm closing this issue because the latest versions of EE7 and EE6 no longer have this issue.
