### ISSUE TITLE
EE 7.1.3: Warning: Could not be converted to int

### ISSUE THREAD

**Issue by Caleydon** [ExpressionEngine/ExpressionEngine#2387]
EE 7.1.3
PHP 8.0

In back ofiice I see following warning

![Alert](https://user-images.githubusercontent.com/2806752/189866160-4b776225-4be8-4c0f-aa13-670de221f811.png)

When I want to upgrade CMS, the "Checking for updates.. " message appear a few minutes and then I get "Up to date! " message that I am using latest version. So I can't upgrade to 7.1.4 via upgrade system.

**Comment by intoeetive** [comment]
@Caleydon thank you for reporting!

Can you try changing line 333 in `system\ee\ExpressionEngine\Service\Alert\AlertCollection.php` to `$url = ee('CP/URL', 'logs/developer')->compile();` and see if that fixes the issue?

As of upgrade issue, can you check for updates manually from settings page? See if you get any errors, otherwise this might be just temporary network issue
