### ISSUE TITLE
Upload to new filedir results in whitescreen

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#253]
**Description of the problem**
I have a site with 3 upload directories. I can upload to them just fine. When I create a new directory, uploading results in a white screen. 

The file is uploaded however and when I sync the directory afterwards, the file does show up in the filemanager.

**How To Reproduce**
Noticed it in 5.2.3. Update to 5.2.4 made no difference.

**Error Messages**
None. White screen after clicking Upload File. Debugging activated.

**Environment Details:**
 - Version: 5.2.4
 - PHP Version 7.2.19
 - MySQL Version 5.7.25-log
 - OS: Linux info 3.0 #1337 SMP
 - Web Server: Apache CGI/FastCGI

**Comment by robinsowell** [comment]
Sounds like it is uploading the file but throwing an error before it can enter it into the database.  That's why it's not showing up in the file manager until after you run the sync.

I can't replicate, though.  

We really want an error if we can get it.  Do you have php error logs and do they show anything?

And if no luck there, you can turn on EE's logging.  In system/user/config/config.php:

```
$config['log_date_format'] = 'Y-m-d H:i:s';
$config['log_threshold'] = '1';
```
Make sure you have a writable log folder a la /system/user/log/.

See if you get anything in there when you whitescreen.

If not, change the threshold to 2 - that will get us some system messages and we can at least see how far it's getting before it bails out.

**Comment by silenz88** [comment]
Today I cannot replicate

**Comment by robinsowell** [comment]
Hrm- yay? 

I wonder what was going on.  If it happens again, try the logging. We really want an error of some sort.

Hopefully it was just a brief server blip.
