### ISSUE TITLE
`{categories show="10&1"}` shows only the first category

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2596]
EE 7.2.2

**Template code with `|`:**
```
{exp:channel:entries channel="somechannel" category="10|1" limit="10" dynamic="no"}
{if count == "1"}
Categories: {categories show="10|1"}<b>{category_name}</b>, {/categories}
{/if}
{/exp:channel:entries}
```
**Output:**
`Categories: Category Name 1, Category Name 10, `

  
**Template code with `&`:**
```
{exp:channel:entries channel="somechannel" category="10&1" limit="10" dynamic="no"}
{if count == "1"}
Categories: {categories show="10&1"}<b>{category_name}</b>, {/categories}
{/if}
<b>{title}</b>, 
{/exp:channel:entries}
```
**Output:**
`Categories: Category Name 1, `

**Comment by intoeetive** [comment]
`&` is not supported operand for `categories` tag pair: https://docs.expressionengine.com/latest/channels/entries.html#show

**Comment by shbchk** [comment]
But what do I do if I need to show current categories for `{exp:channel:entries channel="somechannel" category="{segment_N:url_decode"}`, where categories in `{segment_N}` can be divided by `|` or by `&`? 

It looks like a very needed feature to me, since `{exp:channel:entries}` offers `&` operator for categories.

**Comment by intoeetive** [comment]
@shbchk I appreciate your attempts to push EE to its limits - this unveils us a lot of things that are missing or not working properly.

However for this particular case making `&` behave same way as `|` IMO would not be right, as the logic implies "I want to display categories with ID of 10 _or_ 1", not  "I want to display categories with ID of 10 _and_ 1" - which simply does not make sense.

What could work here is using code like `{categories show="{segment_3:replace find="&" replace="|"}"}` - but in order to make this actually work you'd need to wait until this commit goes into the core (which might take a while though)

https://github.com/ExpressionEngine/ExpressionEngine/commit/07d960e643c823f56d4b503a4449112e293da16f

Or use a custom plugin to do the early replacement

**Comment by shbchk** [comment]
Thanks, Yuri!
