### ISSUE TITLE
Searching for not empty grid field in `{exp:channel:entries}` tag is not possible

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2670]
EE 7.2.5
PHP 7.4.21

I have two entries:
**Entry id 2**: Entry without content in a grid field
**Entry id 1**: Entry with content in a grid field

**What I need**
Show only entries that have rows in a grid field.

**What I tried to do** 

**Try 1**
```
{exp:channel:entries channel="test" search:grid_field="not IS_EMPTY" limit="1"}
{if no_results}
<h1>Nothing</h1>
{/if}

<h1>{title}</h1>
{/exp:channel:entries}
```
Output:
```
Nothing
```

**Try 2**
```
{exp:channel:entries channel="test" search:grid_field:total_rows=">=1" limit="1"}
{if no_results}
<h1>Nothing</h1>
{/if}

<h1>{title}</h1>
{/exp:channel:entries}
```

**Output:**
```
Entry without content in a grid field
```

**Comment by intoeetive** [comment]
@TomJaeger @bryannielsen @matthewjohns0n let's discuss this after new year.
Without deep dive, I think this represents an old issue where if you save Grid without rows, it could be saved as empty array. Which is not qualified for IS_EMPTY check.
I think we could either:
- convert empty arrays to NULL when saving Grid
- make IS_EMPTY check treat empty arrays same as NULL
- do something specifically for Grids???

**Comment by intoeetive** [comment]
After discussion, we concluded that:
a) this needs to be fixed
b) we should look into approach that does not modify the saved data, or how data are saved

**Comment by intoeetive** [comment]
So I had a deeper dive today.

Using `search` parameter against Grid fields (including `IS_EMPTY` check) works fine if the field is set as searchable.
To me, this makes sense, because in case of complex fields like Grid we don't stack join over join to perform search, we merely check the main `field_id_X` column. Which contains searchable data, which is empty if the field is not searchable.

We actually have this documented: https://docs.expressionengine.com/latest/channels/entries.html#searchfield_name

But I wonder if it makes sense to add a message to template debugger when people try doing something like that (search relationship field, or search non-searchable grid) - might save them some time

**Comment by robinsowell** [comment]
OH, I love adding it to the template debugger!  And agree, logic makes sense as far as the behavior- that's what I'd expect.
