### ISSUE TITLE
SVG images + manipulations = 404

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2839]
Sorry, it's me again :)

EE 7.2.9

When I upload `image.svg` in a folder with predefined image manipulation, `{file:manipulation}` tag generates `images/_manipulation/image.svg`, but there is no such file.

**Comment by jcogs-design** [comment]
Haven't checked, but pretty sure that EE image manipulations don't work when applied to SVGs (since they are not supported by GD/GD2 at least) - so am guessing that the processing of the image to apply the manipulation fails (hence no file), but EE's code to apply manipulations doesn't check to see if the file suggested (which I am guessing is simply the filename plus a formulaic path constructed based on trait added to variable) actually exists. It should do ...
