### ISSUE TITLE
Subfolders in File Manager

### ISSUE THREAD

**Issue by ballmannweber** [ExpressionEngine/ExpressionEngine#301]
It would be a great enhancement if the file manager could handle subfolders. 

In a first step, it would not even be necessary to manage them via the interface (create, rename, delete, etc.), but that the File Manager at least recognizes and accepts subfolders created via FTP.

In the next step, the administration could take place directly via the UI.

**Comment by murtaugh** [comment]
I was creating a new feature request, but then I realized this is basically what I was asking for: Syncing subfolders would greatly assist in migrating files from WordPress.

WordPress' media library is organized into chronological folders (`uploads/2020/11`, `uploads/2020/12`, etc). Migrating those files into ExpressionEngine would be made much easier if the EE sync process included subfolders.

To be clear: I'm not asking to be able to create subfolders in the File Manager interface, I just want to be able to create an EE Upload Directory and have the sync operation read all the files in it.

This would make migrating sites over from WordPress significantly easier by:

1. Making media library migration a two-step process (drag and drop the files into an Upload Destination, hit Sync)
2. Eliminating the need to correct `src` values in imported HTML; urls like '/uploads/2020/11/photo.jpg` can remain in place, instead of having to correct them to `/uploads/photo.jpg`.

**Comment by intoeetive** [comment]
Subfolders supported added in ExpressionEngine 7
