### ISSUE TITLE
Channel access: View entries, by others

### ISSUE THREAD

**Issue by intoeetive** [ExpressionEngine/ExpressionEngine#3099]
### Discussed in https://github.com/ExpressionEngine/ExpressionEngine/discussions/3091

<div type='discussions-op-text'>

<sup>Originally posted by **shbchk** March  7, 2023</sup>
Not sure if this is a bug, but there is some inconsistency for sure.

1. Members with the role "OwnEntriesEditors" can edit only entries they created. In the entry list, they can see their own entries only.
2. But pagination suggests that there are a lot of other entries https://github.com/ExpressionEngine/ExpressionEngine/issues/2178
3. And they can see entries created by others in the Relationship fields (if it's enabled).

I wonder if we add an additional action **"View entries, by others"** here?
![2c56916e-2591-4b5b-ad80-4a8e3fd3bf0a](https://user-images.githubusercontent.com/12234507/223495511-bab4bf09-1b3b-4355-a257-d4525644965a.png)

</div>

**Comment by intoeetive** [comment]
If you have "edit entries by others" checked for one channel, you can see (but not edit) entries in all other channels (where you can edit your own entries)

If you don't have "edit entries by others" checked anywhere, then you can't see the entries.

I think we need to make this consistent at the minimum.

**Comment by robinsowell** [comment]
I believe Playa has a setting where you can only select entries you have edit access to it- I'm thinking having the same idea for Relationships makes sense.  You can also set 'current' as the 'Author' option in playa, so that you can only select your own entries.  Those are two seperate things logically and I can see it making sense to have both.  Author and Edit are definitely two different permissions.

By default, I'd want to be able to choose from all of the entries, whether I authored them or can edit them.
