### ISSUE TITLE
File modal on publish- the filter control to add/delete columns doesn't do anything

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3130]
EE 7.2.11 Go to publish an entry with a file field on it.  File field, choose existing.  That opens the modal.  You have the filters to search- that works.  But the controller to add/delete columns doesn't do anything.  It doesn't throw an error, but if I try to add, for example, the ID column, nothing happens:

<img width="1188" alt="Screenshot 2023-03-16 at 12 37 35 PM" src="https://user-images.githubusercontent.com/1181219/225690588-f2ca07fb-58b8-42a7-9d26-f313e6267638.png">

**Comment by intoeetive** [comment]
@Yulyaswan I have investigated this. The problem is that the request is made to URL that should be defined as `EE.viewManager.saveDefaultUrl` - however it is not defined, so the request is made to current URL - which obviously gives an error.

I think we need a way to pass `saveDefaultUrl` as part of the form
