### ISSUE TITLE
Grid field 'auto' doesn't revert back if you narrow then widen browser.

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3173]
Not something that comes up much, but I had a user notice that if you have the grid field set to 'Auto', layout is fine.  Narrow browser, it switches to vertical layout just like it should.  Then if you widen it back to full screen, it stays vertical.  Seems like it should switch back.

I tested, saw the same.  I had text fields in my Grid.

Like I say, not something that happens a lot, but also not what I would have expected.

EE 7.2

**Comment by Yulyaswan** [comment]
@robinsowell 
We can't check the width of the grid relative to the container when we increase the width of the screen.

If the grid has changed its view to a table, then it will always be less than the width of the container.

Therefore, the change only works to reduce the width of the screen.

In order to return to a horizontal view (in case of an increase in the width of the screen), you just need to refresh the page.

Also, after saving the Entry, an automatic check occurs and the grid takes the form, respectively, of its width.

Maybe we need to add some description to the doc

**Comment by robinsowell** [comment]
That makes sense.  Not entirely sure it needs a doc note, but might help.
