### ISSUE TITLE
After file update hook returns incomplete data

### ISSUE THREAD

**Issue by omejelle** [ExpressionEngine/ExpressionEngine#3401]
After uploading an image through the file manager (EE6 latest) i'm getting this in the modal:

```
<div class="err-wrap notice">
	<h1>Notice</h1>
	<h2>Undefined index: dirname</h2>
	<p>user/addons/jcogs_img/ext.jcogs_img.php, line 146</p>
	<ul>
		<li><b>Severity</b>: E_NOTICE</li>
	</ul>
</div>
{"file_id":5912,"site_id":1,"title":"jasper-web","upload_location_id":1,"mime_type":"image\/jpeg","file_name":"jasper-web.jpg","file_size":29932,"description":"","credit":"","location":"","uploaded_by_member_id":16,"upload_date":1684218713,"modified_by_member_id":16,"modified_date":1684218713,"file_hw_original":"290 363","path":"https:\/\/www.site.com\/img\/main\/jasper-web.jpg","thumb_path":"https:\/\/www.site.com\/img\/main\/_thumbs\/jasper-web.jpg","isImage":true,"isSVG":false}
```
It turns out that the hook after_file_update is providing incomplete data

**Comment by intoeetive** [comment]
looks like it's coming from @jcogs-design image extension

**Comment by jcogs-design** [comment]
Yep - on it.

**Comment by jcogs-design** [comment]
What was confusing things was (in part) that in EE6 when a file is uploaded the hook `after_file_update` is being called twice. FWIW in EE7 it only fires once. 
Not sure if `after_file_update` should fire when a file is uploaded (since an existing file is not being updated), and pretty sure even if it does, not sure it should fire twice.
Or am I missing something?

**Comment by intoeetive** [comment]
I recall we had this issue when file in EE6 was actually processed twice when uploading. We certainly got this resolved in EE7, but maybe not in EE6? Probably need to check that again
