### ISSUE TITLE
Multisite causes problems when creating identical field names

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#342]
**Description of the problem**
An EE install with three sites has a field called "Summary" in all three sites.  We deleted the field from one of the sites and then went to re-add it.  We got the error: "**_This field must be unique._**"

**How To Reproduce**
1. Create an EE installation with two sites.
2. Create a field in one site called "sample" with short name "sample"
3. Switch to the second site.  Create a field called "sample" 
4. See error: "This field must be unique."
5. This also applies if you create the field with a different name and then try to change the name to match.

**Error Messages**
<pre><code>
This field must be unique.
</code></pre>

**Screenshots / Videos / Template Code**
<img width="912" alt="Screenshot 2019-12-30 18 17 18" src="https://user-images.githubusercontent.com/49483/71606749-f958ea80-2b30-11ea-89ad-3e77363e1529.png">

**Environment Details:**
 - Version: 5.3.0
 - PHP Version 5.6.40
 - MySQL Version doesn't matter
 - OS: Mac
 - Web Server: Apache

**Possible Solution**
1. Easy: Validate field names only within the current site context
2. Harder: Allow fields to be shared across sites. This requires a lot more code and some UI stuff too.

**Comment by robinsowell** [comment]
Fields are shared across sites now, which is why it's running into a problem.  

Well- don't share file fields, but the others should be just fine and they should show up in the channel settings, so you can assign fields regardless of what site they were originally created on.

Legacy fields can still have the same name on different different sites (and be different in the database), but any new fields created should be site agnostic.
