### ISSUE TITLE
PNG uploads - PNG Manipulations create massive files

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#3432]
Wondered why a few client templates were performing really badly and took a look at the images.

EE is creating larger PNGs for manipulations - here we have the original (553kb) and one at the "mid" size manipulation (4.2mb) 

The largest manip 1920x1920 (14.8mb) is too big to be uploaded to GitHub!

![example_client_uploaded_4000x4000](https://github.com/ExpressionEngine/ExpressionEngine/assets/2526645/eccb7706-4223-4a91-b571-87a8497073ab)

![example_ee_created_1024x1024](https://github.com/ExpressionEngine/ExpressionEngine/assets/2526645/f2e5ca0d-6ec0-46e4-859e-a6f1e8f5390d)

Seems it a scenario where the origin image has large dimensions (in this case 4000x4000). And the output is gigantic file size. Not good for server data not page load.

EE 7.2.7 at time of upload (now updated to 7.2.17 but not tested again). PHP 8.2. GD2.

**Comment by intoeetive** [comment]
@liamcrean I was only able to replicate this with the manipulation quality set to 100.

With the quality set to 90 (default) the image size was 80kb

I would say this is expected behaviour, as 100 means no compression (and your original image is probably using some compression)

I do understand though that this might be not expected for some of site editors. What do you think would be the right thing to do here to provide better user experience? I can think of writing a message to developer log when such thing happens, but maybe something else?

**Comment by liamcrean** [comment]
Thanks Yuri. 

Image quality was set below max (85) so will need to do some testing see if I can isolate issue.

**Comment by intoeetive** [comment]
@liamcrean were you able to isolate the issue as planned?
