### ISSUE TITLE
Date field cannot accept older dates

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3556]
If you put a date with year 1901 or older in a date field- including entry date- it won't validate and you can't save it.

Summarizing: You can't have dates prior to 1901 or after 2038. This is the size limitation of int data types that we use for date columns.

2 possible solutions:
- allow changing column type from int to bigint same as we do for RTE fields. This is quick and easy, because we have the code already
- start using datetime column instead of int for dates. This is IMO the most proper solution and this how it should have been done 15 years ago, but making the change will be more involved.

**Comment by intoeetive** [comment]
I can confirm this issue. You can't have dates prior to 1901 or after 2038. This is the size limitation of int data types that we use for date columns.
As a temporary solution, the user can change the column type to bigint in db and remove this part from validation in `ft.date.php` : `or (is_numeric($data) && ($data > 2147483647 or $data < -2147483647)`
We don't have validation rule like this for entry_date, but the same problem exists for any date - we're using int everywhere
I think that we need to get it fixed and I think there are 2 possible solutions:
- allow changing column type from int to bigint same as we do for RTE fields. This is quick and easy, because we have the code already
- start using datetime column instead of int for dates. This is IMO the most proper solution and this how it should have been done 15 years ago, but making the change will be a pain
