### ISSUE TITLE
Using Template Variable as Parameter does not work

### ISSUE THREAD

**Issue by mackilroy007** [ExpressionEngine/ExpressionEngine#3742]
When using a Template Variable (EE CP --> Templates --> Variables) as a parameter for another expression engine tag inside a template (for example as parameter for the {layout}-tag), the containing tag breaks and the content is omitted. Even if we cut out the middle instance and include the variable directly, the issue persist. 

We have tried using :attr_safe and reducing the length of the expected outputted string to no avail. 

**How To Reproduce**
![grafik](https://github.com/ExpressionEngine/ExpressionEngine/assets/61562994/876f3d9c-636b-47da-b7d2-b9fa24524620)

code:
`{exp:gwcode_categories custom_fields="yes" cat_url_title="{last_segment}" style="linear" limit="1"}
    {layout="seminar/.layout" title="{cat_name}" subtitle="{cat_subtitle}" banner_image="{cat_image}" header_image="<?php echo $headerimage ?>" callback="ja" description="{cat_description}" } 
{/exp:gwcode_categories}`

category instance: 
cat channel => entry => field content cat_description => text including {template variable instance}
![grafik](https://github.com/ExpressionEngine/ExpressionEngine/assets/61562994/0450c9bd-f9d6-45a7-bad3-db798b6d23e7)

variable instance: 
template => template variables => template variable instance => text
![grafik](https://github.com/ExpressionEngine/ExpressionEngine/assets/61562994/a6b6e36f-08aa-4f97-9db8-7696274ffcaf)

**Error Messages**
The outputted result consists out of a partially completed code until the the execution of the description -tag, where it crashes out returning the closing "} on screen, but fails to output the variable text. (also not visible when inspecting the raw code) 
The resulting "} are the 
No error message is displayed.

![grafik](https://github.com/ExpressionEngine/ExpressionEngine/assets/61562994/06e025b1-473e-4eef-a54c-a941a197d2da)

**Environment Details:**
 - Version: 7.3.5
 - PHP Version 7.4.33

**Comment by jcogs-design** [comment]
It might be that your attempt to combine a third-party add-on *and* inline php in an attempt to define the `{layout=}` tag (which [documentation clearly states](https://docs.expressionengine.com/latest/templates/layouts.html#overview) **must come before any module or plugin tags**) is causing the issue. In my experience you cannot include (for example) conditional elements in the content of the `{layout=}` tag - so I would not be surprised if this limitation extends to your more complicated example.

You can get around the limitation this presents simply by using [explicit methods](https://docs.expressionengine.com/latest/templates/layouts.html#layout-variables) to define your variable content in layout variables (either on a previous template in the layout stack or on the one the redirect appears as the first element in the template): these layout variables will then be available in any subsequent templates in the layout stack (just as if you had defined them using the '[static](https://docs.expressionengine.com/latest/templates/layouts.html#static-variables)' method you were trying to. So presumably something like this...

#### Earlier template in stack
```
{exp:gwcode_categories custom_fields="yes" cat_url_title="{last_segment}" style="linear" limit="1"}
    {layout:set name="title"}{cat_name}{/layout:set}
    {layout:set name="subtitle"}{cat_subtitle}{/layout:set}
    {layout:set name="banner_image"}{cat_image}{/layout:set} 
    {layout:set name="header_image"}<?php echo $headerimage ?>{/layout:set}
    {layout:set name="callback"}ja{/layout:set}
    {layout:set name="description"}{cat_description}{/layout:set}
{/exp:gwcode_categories}
```
#### Later template in stack
```
{layout="seminar/.layout"}
```

It is not clear from your description of your issue *why* you need to do the definition of the layout tag in one hit, but depending on your use case it is likely that you could actually put the `layout:set` tags on the **same page** (the example above splits them across two templates) as the redirect - just as a block further down the template - since the redirect doesn't happen until the template it appears on has been completely evaluated.


HTH
🐾

**Comment by mackilroy007** [comment]
@jcogs-design your solution did the trick! 🙌

fyi the php code wasn't a factor, as it didn't have any effect on the issue stated above. I removed it during the debugging stage, but still couldn't solve the underlying issue at hand. In future I'll keep the template layout rules in mind. 

Thanks again 💪
