### ISSUE TITLE
Checkbox in grid validation issues

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3762]
Create a grid, 2 columns.  First column is a checkbox, manually populated.  Use this as the options:

```
Health and safety
Children's mental health
Some stuff
Some more stuff
Yada yada
```

Second column just a text field.

When you try to select 'Children's mental health' the choice doesn't stick.  I also have a user that managed to get a validation error on the checkbox column, where I'm assuming they'd managed to save it at some point and now it doesn't 'match' up.  Didn't show 'Children's...' as selected, but I'll bet that's what was happening.

Note- if you make a standalone checkbox field setup the exact same way, there isn't an issue.  I'm pretty sure it's something about the apostrophe and grid handling it slightly differently.

**Comment by intoeetive** [comment]
The data IS saved, but it does not re-populate when the field is being rendered as React component

EDIT: not React, the issue was in fieldtype... I'm a little concerned though because the original change was introduced years ago to fix exactly same issue, but looks like we has a lot of changes since... https://github.com/ExpressionEngine/ExpressionEngine/commit/5f9ee8299bd2e0c4936bc8ad16fc1a9ce800a4b8
