### ISSUE TITLE
Comment module file missing?

### ISSUE THREAD

**Issue by iammattmartin** [ExpressionEngine/ExpressionEngine#379]
When trying to use the "unsubscribe" link in emails for comment updates, we've noticed this generates blank pages and does not remove the email.

Turning on debug we get:

```
Fatal error: require_once(): Failed opening required '/var/www/xxxx/system/ee/EllisLab/Addons/comment/mcp.comment.php' (include_path='.:/usr/share/php') in /var/www/xxxx/system/ee/EllisLab/ExpressionEngine/Service/Addon/Addon.php on line 688
```

On checking, that files does not exist, as the error does indicate. Also checking the latest release it is missing too.

Is this an oversight and it should be there or another issue entirely?

**Comment by iammattmartin** [comment]
Finding an old version of the file at https://raw.githubusercontent.com/ExpressionEngine/ExpressionEngine/43882902677986751066048580c9045deaade693/system/expressionengine/modules/comment/mcp.comment.php and testing that, seems to now work.

**Comment by dougblackjr** [comment]
@robinsowell Do you have context as to why this was removed? I can pull this back in to the PHP7.4 branch, or adjust accordingly.

**Comment by robinsowell** [comment]
@dougblackjr I'm not sure, though I suspect it was part of moving the comment module more into 'core' and not an optional module.  Something similar was done with Channels.  Both have always been integrated into a lot of the core controllers displays.

Instead of managing comments in a comment control panel, it was moved into core.  But it looks like we lost some functionality doing it.
