### ISSUE TITLE
Must quote tag in template logic after latest update

### ISSUE THREAD

**Issue by benjivm** [ExpressionEngine/ExpressionEngine#3790]
**Description of the problem**

Previously all logic operators have worked like this in my templates:

```
{if {exp:my_addon_bool}}
    // Do something
{/if}
```

After updating from 6.4.6 to 6.4.14 this no longer works, and must be handled like this:

```
{if "{exp:my_addon_bool}"}
    // Do something
{/if}
```

Why is that?

**How To Reproduce**

Compare the two ways to reference a `bool` template tag provided above.

**Environment Details:**
 - Version: 6.4.14
 - PHP Version: 8.1.23
 - MySQL Version: 8.0.34
 - OS: Linux
 - Web Server: nginx

**Comment by benjivm** [comment]
Just for a little more context this is the extent of what the addon does (just an example, obviously):

```php
class FooExample
{
    public bool $return_data = false;

    public function __construct()
    {
        $this->return_data = $this->this_returns_a_bool($_SERVER['FOO']);
    }

    private function this_returns_a_bool(string $foo = ''): bool
    {
        return $foo === 'bar';
    }
}
```

**Comment by intoeetive** [comment]
Hi @benjivm - I wasn't able to replicate the issue on EE 6.4.14 using PHP 8.1 with the sample code you provided.

Is there extra code that needs to be in the template or plugin file to replicate the issue? Also, is only the plugin provided by the addon - or you have module with it as well?

**Comment by benjivm** [comment]
Hi there, thanks for looking into this. It is only a single plugin and I see this behavior across multiple instances (a Linux server and 2 Windows machines) of this project. This is a very long-lived project and has been upgraded since at least EE 3.0 and likely earlier.

To test it out I uninstalled all addons except this one, and created a template with nothing else except the tag.

Here is the exact addon code, `pi.outdated_browser.php`:

```php
<?php

class Outdated_Browser
{
    public bool $return_data = false;

    public function __construct()
    {
        $this->return_data = $this->detectBrowser($_SERVER['HTTP_USER_AGENT']);
    }

    private function detectBrowser(string $userAgent = ''): bool
    {
        $detectRegex = [
            '~MSIE|Internet Explorer~i',
            '~Trident/7.0(.*)?; rv:11.0~',
        ];

        foreach ($detectRegex as $regex) {
            if (preg_match($regex, $userAgent)) {
                return true;
            }
        }

        return false;
    }
}
```

**Comment by intoeetive** [comment]
Hi @benjivm - 

I think I misunderstood you initially - the problem is not that the unquoted usage of tag in conditional returns false, the problem is that it always returns true.

However if I switch to EE 6.4.6 I get PHP warning (not sure if you were not seeing it because of your configured debug level?). And then the change was made in 6.4.12 to prevent the warning: https://github.com/ExpressionEngine/ExpressionEngine/pull/3417

I totally understand how you feel because of changed behaviour. However I think using unquoted tags inside the conditional was never a thing that was supported. It might have worked at some point, but in general you can only use the variables unquoted in the conditionals, if you use tags they need to be quoted (or better, the conditional should be placed inside the tag)

So if adding the quotes works for you, I suggest that you just stick to it

**Comment by benjivm** [comment]
Ah I see what you mean, and yeah I must have missed it due to the logging level. Thanks for your time!
