### ISSUE TITLE
Entry preview doesn't work for not-yet-saved entries when a custom status is set as default for new entries

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3798]
EE 7.3.12, fresh install.

How to reproduce:
1. Create a custom status for your channel, name it "Custom status"
2. Set this new status as default for new entries in the channel
3. Add the new status to your entries tag in a preview template. Like this: `{exp:channel:entries channel='ch' limit='1' require_entry='yes' status='open|closed|custom status'}`
4. Try to open a preview for a new entry, that has not been saved yet - you'll see 404.

**Comment by intoeetive** [comment]
I think with `require_entry='yes'` this might be intended behaviour.

Remember that you can use [`{is_live_preview_request}`](https://docs.expressionengine.com/latest/templates/globals/single-variables.html#is_live_preview_request) conditional variable in your templates

**Comment by shbchk** [comment]
I did some testing and this looks like a strict equality comparison issue. 
It works when the status name is "Custom" and the tag is `status="Custom"`. If the tag is `status="custom"` - it stops working. And it doesn't work with status names with whitespace.

**Comment by shbchk** [comment]
Attaching video :)
[video-convert-1696831931718.webm](https://github.com/ExpressionEngine/ExpressionEngine/assets/12234507/e50a5ed9-efcf-48b3-821c-0c018a54545b)

**Comment by intoeetive** [comment]
What you see here is the difference in comparing string as done by MySQL and PHP.

The most common collation used in ExpressionEngine databases is case insensitive, so `custom` is same as `Custom`. However if the entry is not databases, LivePreview service is trying to convert SQL conditions into PHP conditions, and is using case-sensitive in_array function here. I am not exactly sure just changing the behaviour here will be the right fix, because one could use case-sensitive collation for database as well, and then the behavior will match.

Therefore I will just advise to always provide the status names using their real letter casing.
