### ISSUE TITLE
Structure and url_title construct default  stubs differently

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3908]
A user brought this up- I'm not sure it's actually a bug, but I do think it's worth discussion.

Basically, url_title and structure create the 'default' urls differently in some cases.  For example:

Title field is:
Even voorstellen... Pien de Veen!

Default url title:
even-voorstellen..-pien-de-veen

Default structure:
even-voorstellen-pien-de-veen

It is ok for the two to not match (obviously) but... the behavior isn't what I'd expect.  Thoughts?

**Comment by intoeetive** [comment]
I noticed this as well, and I'm pretty sure already have this reported in GitHub but I can't find it. Now that Structure is a core thing, it would be nice to just make those be the same - but I wouldn't classify this as a bug

**Comment by intoeetive** [comment]
Investigated a bit. Structure (on the backend) is using same code that we use when we enforce automatically generated URL titles. And yes - javascript and PHP code slightly different. Javascript function has separate configuration for `remove_periods`, but also code itself is different.

I'm not sure which one is better (url_title or structure__uri) so that's something we need to decide
