### ISSUE TITLE
7.4 DP When Coilpack is present, upgrade screen does not load

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#3937]
**Description of the problem**

I dropped in the new files from the 7.4 zip file and attempted to load the admin home page and got the following error. When I changed the env to not route through Coilpack, the upgrade screen loaded immediately and I was able to upgrade to 7.4.

<img width="1599" alt="Screenshot 2023-12-06 at 1 21 41 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/53965/6f1fd3d3-4a1a-4f77-919c-bc6a89d04ac7">

PHP 8.2

**Comment by bryannielsen** [comment]
@litzinger I haven't been able to reproduce this on my end.  I created a fresh 7.3.14 site and then downloaded the latest 7.4 DP (33) and extracted it alongside my 7.3.14 folder, moved my 7.3.14 `config.php` file into the 7.4 folder and then renamed my folders so that Coilpack was using the 7.4 install and it prompted me to upgrade and everything seems fine after that.  I also did a fresh install of 7.4 by running `php artisan coilpack --dev` and choosing the latest DP from the top of the install list.  I couldn't get this error with either method.  

I'm thinking you must have two copies of the EE folders being loaded because Coilpack doesn't have this class that's being flagged as being declared twice.  I'm happy to walk through this on Slack if you think there's still a problem but I'll close for now until we can reproduce the issue.

**Comment by litzinger** [comment]
This is my setup. I have coilpack at the root, which has the coilpack.php file system_path set to use the `system` folder in the root. I do have other EE folders but the main `system/ee` is symlinked to the `ExpressionEngine7.4/system/ee` folder. 

<img width="687" alt="Screenshot 2023-12-07 at 7 45 15 AM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/53965/ef45fbe2-d65d-4dee-a3f1-4ca77168432d">
