### ISSUE TITLE
Unreproducable- Entry manager with Cat column showing limits entries to those with cats

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4112]
From slack, I can't reproduce on 7.4.2+ but I wanted a record of it.  Note- he tested local upgrading to 7.4.3 and still had the problem there.

Problem- 2 users, both superadmin, when viewing 1 channel- only filter was the channel filter- they showed different numbers of entries.  1 super admin only showed 8 entries for a channel with 1,000s.  It ended up being the user with only 8 entries had the Category column showing, and when that was set to include in columns, it was only showing entries with categories selected.

I absolutely can't replicate and can't logic out how that could happen AND I not replicate.  But wanted it noted.

per slack:

My coworker and I are seeing different results when trying to view a list of entries in a specific channel (e.g. https://website.com/admin.php?/cp/publish/edit&filter_by_channel=10). When they log in in any of our environments, they only see ~8 entries in that initial view, while I see the expected default of 25 entries.

- There are 1000+ entries in this channel.
- We're both superadmins with no other roles.
- When I log in as them in any environment, I see 8 entries too, so it's not a browser/cookie issue.
- When they change the "Show" count to 50, they see 26 entries, while I see 50.
- I confirmed that all of our settings in the members table are the same too.
- Weirdly, only this channel seems to be affected. Other channels all appear to show the default of 25 on page load.
- Lastly, their pagination shows 166 total pages, while mine shows 79.

Any idea what could be causing this difference in our views?

**Comment by robinsowell** [comment]
AHA- user tested and this pr did fix it https://github.com/ExpressionEngine/ExpressionEngine/pull/3922/files

**Comment by swierczek** [comment]
I can replicate it on a fresh EE install, but you need more than 25 entries in a channel. Edit some of those entries and add categories to them, then make sure to show the Categories column. Now, instead of it returning/showing 25 entries, it actually queries/returns 25 results, _but each entry + single category counts as a result_. i.e. if an entry has 3 categories assigned to it, it would count as 3 rows in the query result, so the end table would only display 23 unique entries instead of 25.
