### ISSUE TITLE
EE6 to EE& upgrade - ckeditor not listed

### ISSUE THREAD

**Issue by clifavenu** [ExpressionEngine/ExpressionEngine#4441]
Hi,
Issue with RTE upgrading from ee6 to ee7. EE7 fresh install has ckeditor and redactorX. EE6 upgrade to EE7 has basic, full, redactor basic and redactor x.  

Checked different installs and same results.

See attached.

Thanks,
![EE6toEE7](https://github.com/user-attachments/assets/a293ac5f-2c4c-41ed-a60f-39f5ee58620c)
![EE7](https://github.com/user-attachments/assets/d6b974c7-2ba0-493b-b175-255adbf9f3a8)

**Comment by intoeetive** [comment]
@clifavenu this is not a bug. Because Redactor has reached it's end of life we still ship it (you create create tool set with it) but we don't install it by default.

As of the names for toolsets, we respect the pre-existing toolset names when upgrading. It looks like the tool sets have been renamed to remove "Ckeditor" part from the name, thus the difference
