### ISSUE TITLE
Unusual warning from CP Files after uploading / replacing a file

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#4511]
**Description of the problem**
Got the following warning when listing a File Upload directory from RedactorX RTE Field (click on add image icon) immediately after uploading / overwriting an image within that directory.

Warnings went away after saving the underlying Channel Entry and re-clicking on the add 'Add Image' icon
```
Warning
unlink(user/cache/jcogs_net/ExpressionEngine_Model_File_UploadDestination/5e19586927dea4c44aa34e7c177489b3): No such file or directory

ee/legacy/libraries/Cache/drivers/Cache_file.php, line 58

    Severity: E_WARNING
```

**Environment Details:**
 - Version: 7.4.11
 - PHP Version 8.2

**Comment by PaulBaileyAtChan** [comment]
+1

Since moving to EE7 (and at the same time to a new server), I've been getting a very similar error when using the file upload modal in the entry manager, to add a file to a textarea field. A typical example is:

```
Warning
unlink(user/cache/default_site/ExpressionEngine_Model_File_UploadDestination/eabe415ac2c6066d3aa77912c9de6891): No such file or directory
ee/legacy/libraries/Cache/drivers/Cache_file.php, line 58
Severity: E_WARNING
```

There will typically be many occurrences of this error in response to a single upload, but I'm not sure what the number correlates with. Despite the warnings, the file upload does seem to work as expected.

(I had thought that I might be getting these errors because of a misconfiguration of cache directory permissions, but they do all look okay to me.)

Environment Details:

- Version: 7.4.11
- PHP Version 8.3

**Comment by intoeetive** [comment]
I think that happens if the file was already deleted by a parallel process. The suggested PR should solve it
