### ISSUE TITLE
Fluid field count doesn't seem to work inside a fluid field group

### ISSUE THREAD

**Issue by stigarildberntzen** [ExpressionEngine/ExpressionEngine#4594]
It seems like the {fluid_content:count} don't work inside a field group when using fluid fields.

For example:
{my_fluid_field}
  {my_fluid_field:my_field_group}
    {my_field_group:my_textarea}
    {my_fluid_field:count}
  {/my_fluid_field:my_field_group}
{/my_fluid_field}

**Environment Details:**
 - Version: 7.5.3
 - PHP Version: 8.2
 - MySQL Version: 10.11.9-MariaDB-cll-lve
 - OS: MacOS
 - Web Server: Linux

**Comment by bryannielsen** [comment]
@stigarildberntzen the `{my_fluid_field:count}` variable doesn't really have a meaning inside the Field Group unless you use the `{fields} ... {/fields}` loop to iterate over the fields within your field group.  In that case the count variable should work correctly.  

Are you trying to get a "count" for the group instead of the field?  I don't believe we have a variable for that but it could be added.

**Comment by bryannielsen** [comment]
@stigarildberntzen we added `count_group` and `index_group` variables in 7.5.5
