### ISSUE TITLE
AJAX reqests still require CSRF token

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#491]
**Description of the problem**
[Per the doc](https://docs.expressionengine.com/latest/development/guidelines/security.html#validating-form-hashes-in-your-add-on): 

> Asynchronous requests that include an HTTP_REQUESTED_BY header (this is set by most popular libraries, such as jQuery) default to being exempt from these checks as they provide a good layer of intrinsic security.

see also forcing it on with ajax:

> While the same origin restriction for AJAX requests provides a good level of security from cross-site request forgery, compromised browser add-ons can send these requests.

If you have AJAX action requests that are performing sensitive operations, then you should consider forcing AJAX CSRF validation for your add-on. This happens on per-class basis using a marker interface. You simply implement the Strict_XID interface on your action receiving class:

BUT a simple ajax post request triggers a secure form error.  Either the docs or the code appears wrong.

**How To Reproduce**

Create template site/test1

```Hey.

<script
			  src="https://code.jquery.com/jquery-1.11.3.min.js"
			  integrity="sha256-7LkWEzqTdpEfELxcZZlS6wAx5Ff13zZ83lYO2/ujj7g="
			  crossorigin="anonymous"></script>
		
		
	<script>
		function loadMoreArticles () {
			entry_list_articles = 123;
			
			if ('' == 'csrf') {
				data = {
					csrf_token: '8694ffe10f74b14e78e1ac4c3875c7b4732a0d27',
					entry_list: entry_list_articles
				}
			} else {
				data = {
					entry_list: entry_list_articles
				}
			}

			$.ajax({
			    headers: {
        'X-Requested-With': 'XMLHttpRequest',
		'X-Requested-By': 'XMLHttpRequest'
    },
			
				url: '/site/test2',
				method: 'POST',
				data,
				success: function (response) {console.log("Success!");},
				error: function (response) {console.log("Error!");}
			});
		}

		loadMoreArticles();
	</script>

You.
```

Create site/test2
```
<script>
	loaded_entries_articles = 124;
	// csrf_token = "8694ffe10f74b14e78e1ac4c3875c7b4732a0d27";
</script>
```

Load up site/test1 check the console and see it fail.  If you send a token, it's good.

**Possible Solution**

We either need to actually default ajax to not requiring it, or we need to tweak the docs.

Where we determine whether csrf checks are done is in system/ee/legacy/core/Security.php around line 112:
```
		if (($flags & self::CSRF_EXEMPT) || // exempt trumps all
			(AJAX_REQUEST && REQ != 'CP' && ! ($flags & self::CSRF_STRICT)) || // non-cp ajax only gets checked for strict mode
			bool_config_item('disable_csrf_protection')) // disabled
		{
			$is_valid = TRUE;
		}
```

**Additional context**

**Comment by Sungodragon** [comment]
Will this be fixed w.r.t https://github.com/ExpressionEngine/ExpressionEngine/pull/1009 ?

**Comment by intoeetive** [comment]
It's two years since this has been reported, but I just had a deeper look into it and have something to say.

The documentation piece @robinsowell is quoting is referring specifically to add-on and actions provided by those add-ons. 

If you send AJAX request to a page, the CSRF token is required (and this is also [in the docs](https://docs.expressionengine.com/latest/development/guidelines/security.html#csrf-tokens-in-templates)). I don't know if that is something we want to change, since it has been like this since very early versions of EE. I also don't think it's possible to set CSRF exemption on template level, because the check is being run before the template engine starts.

It is still possible to completely disable CSRF protection by setting `$config['disable_csrf_protection'] = 'y';` but is not really thing we could recommend for most of the sites.
