### ISSUE TITLE
Hide a category group in a layout and lose stored data

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#499]
**Description of the problem**
If you had a category group via a layout, saving the entry can lose any stored category data.

**How To Reproduce**
Create 2 category groups.  Go make an entry.  Pick a category or two in each of the groups.

Then create a layout and hide one of the groups- leave the other one showing.

Edit your entry, resaving it.  Now the category group that was hidden has no categories selected.  You've lost that data.

Note- if you only have 1 category group, you can't replicate the issue.  It's having 2 and hiding one that's a problem.  I'm pretty sure the check on visibility isn't taking into account that you can have multiple groups, some showing and others not.

**Environment Details:**
 - Version: [e.g. 5.3.2]
 - PHP Version [e.g. 7.1]

**Comment by Harold-git** [comment]
Hi Robin,
I've upgraded from 5.3 to 5.4 especially to be able to hide categories in the layout.
The issue is that members added specific categories to entries and we want to keep the category added to it. But we don't want them to tag new entries to those categories so we would like hide those categories.
Only when clicking on 'Hide' or 'Collapse' it still won't stick when saving to the layout.
Best regards,
Harold
