### ISSUE TITLE
"Pending" member group is not an option in Member Manager group filter

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#537]
**Description of the problem**
On the main Members page, you can filter by member group, but "Pending" does not show up in this menu:

/admin.php?/cp/members

**How To Reproduce**
1. Go to the Member manager. It's pretty easy to confirm.
2. You CAN get to this if you go to Member groups, and then click on the number next to Pending:
admin.php?/cp/members&group=4

**Screenshots / Videos / Template Code**
<img width="271" alt="Screen Shot 2020-10-06 at 22 57 32 " src="https://user-images.githubusercontent.com/49483/95289348-c3ffcc80-0827-11eb-9d1b-80f4ff8066fe.png">

**Environment Details:**
 - Version: 5.3.2
 - PHP Version N/A
 - MySQL VersionN/A
 - OS: N/A
 - Web Server: N/A

**Possible Solution**
Seems deliberate.  Don't know why.

**Additional context**

**Comment by intoeetive** [comment]
Thank you for the report!

This might have been omited for a reason, since there is "Pending Activation" link in sidebar.

Provided there is sufficient functionality in EE5 and this will be changed in EE6, we will likely not work on this one - but if you feel there is strong reason to implement this in v5, please communicate!
