### ISSUE TITLE
Image processing for member profile images (avatars)

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#580]
It would be very helpful for image processing to be applied to member photo uploads

Currently, without any image processing, embedding member photos in the front-end templates is a very high bandwidth proposition. Most people upload selfies so storing them and showing them is very inefficient. 

I have not been able to come up with any alternative other than severely limiting the size of the uploaded image but, as I stated, since most people upload photos from their phone this file size limitation would exclude a vast majority of users from uploading images of themselves.

Thanks.

**Comment by intoeetive** [comment]
Because member photos as not supported in EE6 (only avatars are) I am going to close this.

The avatars can be restricted to maximum width and height, and also with the inclusion of https://github.com/ExpressionEngine/ExpressionEngine/pull/1685 avatars will be automatically resized during front-end upload.
