### ISSUE TITLE
Channel Form Assets not Loading

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#588]
Using a simple Channel Form template I'm unable to load the stylesheet for advanced fields. I'm using the link provided in the documentation: 

`<link href="{path='css/_ee_channel_form_css'}" type="text/css" rel="stylesheet" media="screen">`

Channel form works but the stylesheet gives a 404.

**Comment by intoeetive** [comment]
This worked on my testing. How does the full compiled link look like? (the one that gives 404)

**Comment by VarenSwaab** [comment]
The compiled url looks like this: 
`<link href="https://***.dev/css/_ee_channel_form_css" type="text/css" rel="stylesheet" media="screen">`

It just refuses to load a file. I should note that I'm using MSM and this is a secondary site. So far everything else about the site works well.

**Comment by VarenSwaab** [comment]
This is more of a feature request but I'm using the channel form on a site that needs to be very phone friendly. In past versions of EE, some fields rendered very poorly on a small screen. I notice there is still no option to load a cform stylesheet optimized for a small screen. Has this been addressed in EE6 or are phones still being treated poorly?

**Comment by intoeetive** [comment]
so am I correct assuming you load the page from `siteB.com` and the `link href` points to `siteA.com`? Is the `channel:form` tag for channel that is on site A or site B?

As a general note, improving the front-end editing expirience is on our roadmap in the top list of priorities. However we're just not there yet. The `css/_ee_channel_form_css` is generally the same that for EE5, so you will not see much difference.

**Comment by VarenSwaab** [comment]
> so am I correct assuming you load the page from siteB.com and the link href points to siteA.com? Is the channel:form tag for channel that is on site A or site B?

@intoeetive yes, that's correct. 

> As a general note, improving the front-end editing expirience is on our roadmap in the top list of priorities.

This is good to hear. EE is not very mobile friendly, especially with fieldtypes. 87% of my users are on mobile devices and I have always struggled to work-around the shortcomings of the front-end channel form. Making EE more mobile friendly is a good way to keep it relevant and expand it's potential uses. IMHO.

**Comment by intoeetive** [comment]
@VarenSwaab for a moment I thought that I am able to replicate this, but only because I had `$assign_to_config['site_url']` set to wrong URL in `index.php` file for secondary site.
Also, I noticed that your compiled URL to CSS does not have `index.php` - if you have `Website index page` set to empty string in site settings, make sure you have `.htaccess` file in place https://docs.expressionengine.com/latest/installation/best-practices.html#removing-indexphp-from-your-urls

For now, I will close this issue, but if you still expirience problems after checking/fixing the above, I will be happy to reopen it.
