### ISSUE TITLE
The {count} variable is broken in {exp:channel:entries} tag

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#631]
The {count} variable is broken in the channel:entries tag  when  the search:field="" parameter is used.

This example works and {count} increases one numeral for each entry:
```
{exp:channel:entries channel="zones" limit="100"}
<h2>{title} - {count}</h2>
{/exp:channel:entries}

```
This example does not work. The {count} parameter stays at "1" for each entry:
```
{exp:channel:entries channel="zones" limit="100" search:sz_city="=London"}
<h2>{title} - {count}</h2>
{/exp:channel:entries}

```

**Comment by intoeetive** [comment]
@VarenSwaab I wasn't able to replicate that on latest EE6 beta.
Please make sure this is not some kind of variable conflict (e.g. because of nesting the code) and also try to convert field to search by into simple text field (if it's not already).
Closing the issue for now, but if you still can replicate this even if it's the only code that you have, please reopen with a comment

**Comment by VarenSwaab** [comment]
Yuri, The code shown above was the only code on the page during my testing so the possibility of any conflicts with any other code or nesting is not possible. This error has been reproduced on my site on various pages using various approaches.
