### ISSUE TITLE
How can we create the custom relation field for the addon?

### ISSUE THREAD

**Issue by Bhavin9898** [ExpressionEngine/ExpressionEngine#661]
I am trying to create the custom relation field for the member list. But When I changed the name of the "Relate Entry" button using the below Jquery then it is affected for all the relation field on that page.

`ee()->javascript->set_global([
			'relationship.publishCreateUrl' => ee('CP/URL')->make('publish/create/###')->compile(),
			'relationship.lang.creatingNew' => lang('creating_new_in_rel'),
			'relationship.lang.relateEntry' => lang('select_member'),
			'relationship.lang.search' 		=> lang('search'),
			'relationship.lang.channel' 	=> lang('member_role'),
			'relationship.lang.remove' 		=> lang('remove'),
		]);`
So EE provides the way to applies those Jquery for only the specific field instead of all the relation field on that page.

Please ignore as issue if there is the way to do it.

**Comment by intoeetive** [comment]
As the function name says, you're manipulating globals here - which are reusable by all fields/components on the page.
In the current state of Relationship component, there is not much room for customization if you need to create different field type.
You would likely need to create your own component that would work on top of "relationship" javascript.
Since this is neither bug report not feature request, I'm closing this issue
