### ISSUE TITLE
Channels across multiple websites

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#701]
It will useful to be able to use a channel on multiple websites powered by EE.
Right now, each site have specific channels when you enable multiple sites options.

**Comment by stephengalbraith** [comment]
Are you meaning for channels to be available in the CP across multiple sites? Otherwise, https://docs.expressionengine.com/latest/msm/code.html states that the `site` parameter is available on several tags, including the Channel module (`exp:channel:entries` for example) so multiple sites can show channels across any site.

**Comment by digicali** [comment]
I see. is it also possible to send content to a channel located in site A from site B ?

**Comment by digicali** [comment]
Ok, i just tested and it works. This suggestion can be closed
