### ISSUE TITLE
A file field cannot send content to another site

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#703]
I'm using the File Field on a multiple websites powered by EE 6

A user can create tickets from site B to channel Tickets on site A.
For all data it works except files. 
I add the hidden field for the data folder (ID 5)
<input type="hidden" name="fd_attachment_directory" value="5"/>
But nothing is send to this folder.

**Comment by ops-andy** [comment]
fixed in 6.0.1

**Comment by digicali** [comment]
what is the tag to add to send the data to another site? doesnt' seems to work if you just put the id of the directory

**Comment by intoeetive** [comment]
Please make sure you use [site](https://docs.expressionengine.com/latest/channels/channel-form/overview.html#site) parameter for you channel form tag.

Also instead of using [manually constructed file field](https://docs.expressionengine.com/latest/channels/channel-form/examples.html#entry-forms-using-manually-constructed-file-field) try making it auto-populate using `{form:field_name}` or `{custom_fields}` pair
