### ISSUE TITLE
Uploading images to a file grid doesn’t work

### ISSUE THREAD

**Issue by simonmalz** [ExpressionEngine/ExpressionEngine#737]
I’m working with the official release of EE6.

When uploading several images to a file grid, only one shows up. The others are saved within the files, but don’t show up within the entry.

Uploading images one by one seems to work though.

**Comment by pyrobob83** [comment]
I get the same issue, though in my case the File Grid is within a Fluid Field (I have not tested a standalone File Grid).

This next part might be a separate issue, but this is how I noticed this, so I'll go ahead and mention it... let me know if I should open a new issue.  After this happens for me in my File Grid inside a Fluid Field and I try to "Choose Existing" to manually add images one by one, my File Manager popup window isn't refreshing the cache, so it still doesn't show the new image thumbnails that should be available even though they do show in the main Files > Directory list.  A hard refresh on the Publish screen doesn't help either - I guess since the File Manager popup is AJAX... so there's no way to clear the cache to show latest images that do exist in that directory.  The only solution is to clear all browser cache or switch to a private/incognito tab (in Firefox anyway... haven't tested elsewhere)

**Comment by simonmalz** [comment]
I actually have the same setup, @pyrobob83 described it in better detail. My File Grid is also within a Fluid Grid. After uploading, only one image shows up while the others aren’t displayed in the File Manager.

**Comment by intoeetive** [comment]
@pyrobob83 would you mind posting that as separate issue? We are trying to stick to one problem per GitHub issue.

I'm going to close this one as we already have duplicate issue https://github.com/ExpressionEngine/ExpressionEngine/issues/693

**Comment by pyrobob83** [comment]
@intoeetive #693 doesn't appear to be the exact same issue as this.  Even if uploading less than 5 images to a File Grid field and all images are technically uploaded successfully, only 1 row in the grid actually remains visible after the uploads complete.  Here's a video that hopefully explains this issue.  In this video, I'm dragging in 3 images, which all do get uploaded to the correct directory, but only the last one to finish uploading creates a 'row' in the File Grid:

https://user-images.githubusercontent.com/8193519/103558928-9cde8880-4e72-11eb-9c2f-cb2f345f7ad3.mp4

**Comment by simonmalz** [comment]
That’s exactly the problem I have. Thank you for the video, @pyrobob83.

**Comment by pyrobob83** [comment]
UPDATE: I just tested this same "Image Gallery" File Grid as a 'standalone' field (ie, not inside a Fluid) and it does the same thing.

**Comment by intoeetive** [comment]
Thanks @pyrobob83!

@TomJaeger this seems to be separate Javascript issue, can we ensure it gets addressed as well?

**Comment by ops-andy** [comment]
fixed in 6.0.1
