### ISSUE TITLE
Collection filters vs. actual collection get

### ISSUE THREAD

**Issue by gb-lin** [ExpressionEngine/ExpressionEngine#895]
When using with() and filter() to fetch models, I'd expect the returned objects contains the collections as a whole rather than trimmed, or at least have the option to retain the whole collections.

For example,
`$members_query = ee('Model')->get('Member')->with('Roles')->filter('Roles.role_id', 'IN', [1, 5])->order('email', 'ASC')->all()->indexBy('member_id');`
The above would return a list of members with Role 1 and 5, which is good. However, if I then try to output the roles when looping through the members,
`$role_ids = $member->Roles->pluck('role_id');`
I would only get Role 1 and 5 even though some of the members may have other roles.

Is there another way to use with() and filter() solely for filtering on the main entities but not affecting the collections attached in the result?

**Comment by intoeetive** [comment]
You would need to use `$member->getAllRoles()` (we'll get this documented soon)

**Comment by gb-lin** [comment]
Hey @intoeetive this is still not working, maybe the function is still not complete in 6.0.2? I took a look at the Member model and found that the getAllRoles() is still loading the roles from $this->Roles which is getting trimmed by the with() and filter(). I'm not using the RoleGroup in this instance.

I can help write the code, I just want to confirm
1. if the behaviour I'm describing make sense (to get the full list of Roles even if I'm filtering members with certain roles)
2. if the above is true, where should that happen? in the getAllRoles() method or the filter() method?

**Comment by intoeetive** [comment]
Reopening this...

@gb-lin having re-read your initial post, it looks like you have both chunks of code in the same function - it that correct? And the second one seems to be applying `filter()` from the first one?
If that is your issue, can you confirm that by removing or modifying `filter()`?

Maybe posting your full code together with expected and received results might help to better understand the issue

**Comment by gb-lin** [comment]
```
<?php
$members_query = ee('Model')->get('Member')->with('Roles')->filter('Roles.role_id', 'IN', [1, 5])->all()->indexBy('member_id');

$members = [];
foreach ($members_query as $member) {
	$roles = $member->getAllRoles(); // I want to get all roles this member is included in rather than the filtered roles [1,5]

	$role_ids = $roles->pluck('role_id');
	$roles = $roles->getDictionary('role_id', 'name');

	if (in_array(6, $role_ids)) { // Some members are in roles 6, but the role is removed from the Roles collection
		echo 'Also in role 6!';
	}
}
```

**Comment by gb-lin** [comment]
@intoeetive like I said I'm ok to take on the coding of this if you point me to where the changes should happen.

**Comment by intoeetive** [comment]
@gb-lin thank you for offering help. I have tried your code and I can see the issue. There are several ways we could solve this, so we'll need to make few architectual decisions before actually writing the code. 

For the time being, this should work:
instead of `$roles = $member->getAllRoles();`
use `$roles = ee('Model')->get('Member', $member->getId())->first()->getAllRoles(); `

**Comment by intoeetive** [comment]
@gb-lin so in order to make this work, you need to modify your code (and we'll need to update the docs). Let me explan how and why:

[`filter()`](https://docs.expressionengine.com/latest/development/services/model/fetching.html#filters) method used when fetching the models is part of model Query Builder and as such is modifying the underlying SQL query. Therefore, in your example you will get only subset of `Roles` - those that match your filter criteria. This falls in line with the logic of code in general, but might be not desired result for certain applications.

To solve this, you would need to use [`aliases`](https://docs.expressionengine.com/latest/development/services/model/fetching.html#aliasing), which means you'll need to relate to `Roles` twice - one time for providing the relationship for the filter and the other time for actually fetching the roles. The corresponding code chunk would look something like  `->with('Roles', 'Roles as MatchingRole')->filter('MatchingRole.role_id', 'IN', [1, 5])`. Here you would be aliasing `Roles`under different name and proving that for `filter()`, and it will be used solely for filtration purposes; and you also specify the original `Roles` relationsip to be eager-loaded for populating. **Important** is that non-aliased name of the model should be listed **before** the aliased one, otherwise it will get over-written.

We will be updating the docs to mention this.

In addition specifically to your case, you'll probably also want to include `PrimaryRole` with your query, as in certain cases it might not be in `Roles`. So the final code might looks something like
`ee('Model')->get('Member')->with('PrimaryRole', 'Roles', 'Roles as MatchingRole')->filter('PrimaryRole.role_id', 'IN', [1, 5,])->orFilter('MatchingRole.role_id', 'IN', [1, 5])->all()->indexBy('member_id');`
