### ISSUE TITLE
[Discussion Forum] Exception whilst posting in the forum

### ISSUE THREAD

**Issue by joaovideosmart** [ExpressionEngine/ExpressionEngine#905]
Hi,

After our upgrade to EE6 we start having an exception when posting on our forum.
The post still goes through, but it seems that after posting it tries to retrieve the thread and it throws an exception.

The issues seems to be that it cannot find class **Forum** on Registry.expandAlias().
```
 if (! class_exists($name)) {
                throw new \Exception("Unknown model: {$name}");
            }
```

Thanks.

Full stack trace bellow:

```
Exception Caught
Unknown model: ee:Forum
ee/ExpressionEngine/Service/Model/Registry.php:94

Stack Trace: Please include when reporting this error
#0 ee/ExpressionEngine/Service/Model/Registry.php(111): ExpressionEngine\Service\Model\Registry->expandAlias('ee:Forum')
#1 ee/ExpressionEngine/Service/Model/DataStore.php(161): ExpressionEngine\Service\Model\Registry->getMetaDataReader('ee:Forum')
#2 ee/ExpressionEngine/Service/Model/Query/Select.php(145): ExpressionEngine\Service\Model\DataStore->getMetaDataReader('ee:Forum')
#3 ee/ExpressionEngine/Service/Model/Query/Select.php(87): ExpressionEngine\Service\Model\Query\Select->selectModel(Object(ExpressionEngine\Service\Database\Query), 'ee:Forum', 'ee_m_Forum')
#4 ee/ExpressionEngine/Service/Model/Query/Select.php(49): ExpressionEngine\Service\Model\Query\Select->buildQuery()
#5 ee/ExpressionEngine/Service/Model/DataStore.php(275): ExpressionEngine\Service\Model\Query\Select->run()
#6 ee/ExpressionEngine/Service/Model/DataStore.php(220): ExpressionEngine\Service\Model\DataStore->runQuery('Select', Object(ExpressionEngine\Service\Model\Query\Builder))
#7 ee/ExpressionEngine/Service/Model/Query/Builder.php(138): ExpressionEngine\Service\Model\DataStore->selectQuery(Object(ExpressionEngine\Service\Model\Query\Builder))
#8 ee/ExpressionEngine/Service/Model/Query/Builder.php(55): ExpressionEngine\Service\Model\Query\Builder->fetch()
#9 ee/ExpressionEngine/Addons/forum/mod.forum_core.php(5470): ExpressionEngine\Service\Model\Query\Builder->first()
#10 ee/ExpressionEngine/Addons/forum/mod.forum.php(282): Forum_Core->submit_post()
#11 ee/legacy/libraries/Actions.php(175): Forum->submit_post()
#12 ee/legacy/libraries/Core.php(522): EE_Actions->__construct(true, Object(Closure))
#13 ee/legacy/controllers/ee.php(51): EE_Core->generate_action(true)
#14 [internal function]: EE->index('2223')
#15 ee/ExpressionEngine/Core/Core.php(251): call_user_func_array(Array, Array)
#16 ee/ExpressionEngine/Core/Core.php(111): ExpressionEngine\Core\Core->runController(Array)
#17 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
```

**Comment by ops-andy** [comment]
@joaovideosmart are you still experincing this issue on 6.0.3? I am unable to replicate. We may need you to open up an EE support ticket and have someone dig deeper into your setup.

**Comment by thisisjamessmith** [comment]
I don't know whether this is the "correct" fix, but the following worked for me:

1. EE seems to be looking for a model named `ee:Forum`, however its correct name appears to be `forum:Forum`. There are 3 locations that need updating:

https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Addons/forum/mod.forum_core.php#L5470
https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Addons/forum/mod.forum_core.php#L6986
https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Addons/forum/Service/Notifications.php#L92

2. Then additionally I updated the subsequent lines in each of the 3 cases above to pass the forum variable into the `getModeratorEmailString` method as that was throwing a new warning:

`... $forum->getModeratorEmailString();` -> `... $forum->getModeratorEmailString($forum);`

3. And finally updating the `getModeratorEmailString` method to accept the `$forum` arg:

https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Addons/forum/Model/Forum.php#L239

`public function getModeratorEmailString()` -> `public function getModeratorEmailString($forum)`

This fixes the issue for me (the site in question is the same site as the original poster, which we have recently inherited).

It's possible that you were unable to replicate before because you didn't set up any moderators, which these code blocks all seem to relate to.

**Comment by intoeetive** [comment]
Closing this out as we haven't able to replicate and got no further reports of this behavior.

If you experience the bug again, please open the issue in Forum repo: https://github.com/ExpressionEngine/Forum/issues
