### ISSUE TITLE
Issues with RTE when used in channel:form

### ISSUE THREAD

**Issue by DesignWorkshop** [ExpressionEngine/ExpressionEngine#91]
**Description of the problem**
When using an RTE with the channel:form tag the link formatting button doesn't open the window. The bold and italic buttons don't show the formatting on the RTE. If you view the source the bold and italic markup has been added.

Screenshot 2019-01-16 at 16.50.00.png show the front end with the bolding.
Screenshot 2019-01-16 at 16.50.12.png shows the code with the bold tags.

![screenshot 2019-01-16 at 16 50 00](https://user-images.githubusercontent.com/3585933/51264647-e5af8500-19ae-11e9-97e5-1a3db522b72b.png)
![screenshot 2019-01-16 at 16 50 12](https://user-images.githubusercontent.com/3585933/51264654-e8aa7580-19ae-11e9-8c5a-38a3cc89d42a.png)

**How To Reproduce**

1. Create field with Rich Text Editor field type
2. Assign to channel
3. Use channel:form tag to enable front end entry
4. Try to format text with a link and bold

**Error Messages**
the Console show the error below.

<pre><code>downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:0) source: http://local.domain.com.192.168.1.206.xip.io:8888/themes/ee/asset/fonts/fontawesome-webfont.eot</code></pre>

**Template Code**

<pre><code>{exp:channel:form channel="blog" allow_comments="yes" return="my-activities" author_id="logged_in_member_id" include_jquery="no"}	
	<lable>title</lable>
	<input name="title" type="text">
	 {field:blog_content}
	 {field:blog_image}
	{category_menu}
        <label for="categories">Categories</label>
        <select name="category[]" id="categories" size="4" multiple="multiple">
                {select_options}
        </select>
    {/category_menu}	
	<input type="submit" name="submit" value="Submit">	
{/exp:channel:form}</code></pre>

**Environment Details:**
 - Version: 5.1.2
 - PHP Version 7.2.10
 - MySQL Version 5.7
 - OS: macOS
 - Web Server: MAMP

**Possible Solution**

**Additional context**
The formatting shows when viewing the entry in the system enviroment.

**Comment by kevincupp** [comment]
Sorry for your trouble and thanks for the report. We'd prefer separate problems have separate issues, but here's a rundown of where I think each of these stand

* The link dialog problem likely started here: 62f21c4f68bc981e3a9e8fd1904687eb7ad8e692 Looks like the link tool will need a regular dialog option to fall back on.
* The issue with bold and italics styles not showing is due to some CSS rules, namely `#cform b` and `#cform i` setting the font style and weight to be normal. You can override these selectors if you need a quick fix. Pinging @jmathias so it's on his radar.
* I'm not able to reproduce the error you're getting about Font Awesome, it looks like the glyphs are loading fine in your screenshots.

**Comment by DesignWorkshop** [comment]
Regarding the link dialog box, using the js file from 62f21c4 produced the error below

TypeError: EE.rte.link.dialog is undefined on this line.

`this.$error = $('<em class="ee-form-error-message"/>').text(EE.rte.link.dialog.url_required);`

**Comment by kevincupp** [comment]
Yes, I didn't mean that if you revert the commit that it'll work, just mentioning that it's likely the fundamental change that broke this since it made the link tool use control panel modals which aren't available in channel form. It was done over multiple commits, and there is separate commit that removed the `dialog` property from that JavaScript object mentioned in your error, so that is what's causing the error you are seeing.

**Comment by j1chavarin** [comment]
Just wanted to add that the issue with the bold and italic styles is not only styling. Once that markup has been added, when you highlight and try to remove either bold or italics it does not work.

**Comment by adster101** [comment]
Can confirm the above issues with bolding, italicising etc. CSS conflicts mean it doesn't show the applied style and you cannot them remove the styles.

**Comment by adster101** [comment]
Happy to look into a fix if anyone can point me inthe right direction?
