### ISSUE TITLE
Label field is too wide and hide the "Delete row"

### ISSUE THREAD

**Issue by benoitlemay** [ExpressionEngine/ExpressionEngine#996]
I tried to reproduce the bug but it's inconsistent.. thought it was when i paste to many characters... 
Good news is when we save the field.. problem is solved..  Then it's not a big issue.. It's just you cannot delete a Row on the fly when it occurs.. 

EE 6.0.3
Chrome
![image](https://user-images.githubusercontent.com/11052162/113375247-00c30100-933d-11eb-888f-c1bc1a25cf9a.png)

**Comment by johnfuller** [comment]
Adding another note here on what I believe happened. Since the min and max width is set to 100% in the CSS, you can only make the text field wider, but not smaller. If you go outside the parent, then it pushes the delete controls outside the parent as well. Given the intent that the width should be 100% of the parent, then we can simply override the default (in some browsers) resize control so that you can only resize vertically (not horizontally.) There are other approaches we could take, but allowing the field to resize past the parent could break in other areas where the element is being used.
